/**
 * Regenerates fzf-parity.json from the real fzf binary.
 *
 *   brew install fzf
 *   node src/lib/fzf-parity.gen.mjs
 *
 * Run by hand, never in CI — the point of the committed fixture is that the
 * test suite gets fzf's answers without needing fzf. Re-run it when bumping
 * the port to track a new fzf release, and read the diff: a change here is a
 * change in how the switcher ranks, not a formatting churn.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Real understory project names, plus shapes that exercise the parts of the
// scoring a kebab-case list never reaches: camelCase, digits, dots, slashes,
// fzf's delimiter class, and repeated leading characters.
const CORPUS = [
  "awslogin", "bark", "cache-reaper", "canopy-cli", "canopy-data-gateway",
  "canopy-data-mcp", "canopy-github-ingest", "canopy-transformations",
  "commission-accounting", "commission-admin", "commission-dashboard",
  "company-data-check", "contact-product-interest", "customer-date-missing",
  "data-fx-rates", "dynamo-ingest", "finance-deploy", "forage", "forest",
  "gateway-hubspot", "gateway-load-shed", "giftcard-service", "gitnow", "snag",
  "apps/forage/frontend", "src/lib/colors.js", ".github/workflows/ci.yaml",
  "release-please-config", "some.dotted.name", "v2.10.3-rc1",
  "fooBarBaz", "XMLHttpRequest", "k8s-operator", "user2fa", "1password",
  "cxxxxcxxp", "cxxxxxxxp", "a/b/c:d;e|f", "ab", "ba", "aab", "aba",
];

const QUERIES = [
  // What people type.
  "cdg", "comm", "transf", "cache", "gw", "cg", "can", "ing", "fo", "dash",
  "git", "gh", "ci", "cdgw", "cda", "ct", "cp", "gate", "load", "svc",
  // Prefix / substring / acronym / scattered, against each other.
  "c", "ca", "cd", "co", "da", "de", "ds", "fx", "mcp", "rc1",
  // The scoring corners.
  ".", "-", "/", ":", "2", "3", "8s", "2fa", "1p", "bb", "xhr", "fbb",
  "a", "ab", "ba", "aa", "cxp", "ccp", "ns", "yaml", "js", "json",
];

const filter = (q) => {
  let out;
  try {
    out = execFileSync("fzf", ["--filter", q, "-i"], { input: CORPUS.join("\n") });
  } catch (error) {
    // fzf exits 1 when nothing matched, which is an answer, not a failure.
    if (error.status !== 1) throw error;
    out = error.stdout ?? "";
  }
  return out.toString().trim().split("\n").filter(Boolean);
};

const version = execFileSync("fzf", ["--version"]).toString().trim();

writeFileSync(
  fileURLToPath(new URL("./fzf-parity.json", import.meta.url)),
  JSON.stringify(
    {
      _: "Generated by fzf-parity.gen.mjs — do not edit by hand.",
      fzf: version,
      corpus: CORPUS,
      expected: Object.fromEntries(QUERIES.map((q) => [q, filter(q)])),
    },
    null,
    2,
  ) + "\n",
);

console.log(`wrote fzf-parity.json for ${QUERIES.length} queries (fzf ${version})`);
