// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DescribeRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DescribeResponse {
    /// Human-readable summary of what this provider releases to, shown next to the
    /// destination in forest.
    #[prost(string, tag="1")]
    pub description: ::prost::alloc::string::String,
    /// Metadata this provider accepts, beyond `generic`'s own `provider_url` and
    /// `provider_token`. forest enforces `required` at destination-creation time;
    /// everything else is for rendering and for the provider's own validation.
    #[prost(message, repeated, tag="2")]
    pub fields: ::prost::alloc::vec::Vec<MetadataField>,
    /// Whether Execute handles RELEASE_MODE_PLAN. When false, forest does not offer
    /// a plan for destinations backed by this provider.
    #[prost(bool, tag="3")]
    pub supports_plan: bool,
    /// Optional identifier for the type being implemented, e.g. "understory/ecs@1".
    /// Logged with each release so it is clear which provider served it.
    #[prost(string, tag="4")]
    pub type_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetadataField {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub label: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(bool, tag="4")]
    pub required: bool,
    /// Rendering hint: "text", "url", "number", "password", …
    #[prost(string, tag="5")]
    pub field_type: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub default_value: ::prost::alloc::string::String,
    /// Credentials. forest redacts these in API responses and never logs them.
    #[prost(bool, tag="7")]
    pub sensitive: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteRequest {
    #[prost(enumeration="ReleaseMode", tag="1")]
    pub mode: i32,
    #[prost(message, optional, tag="2")]
    pub destination: ::core::option::Option<Destination>,
    #[prost(message, optional, tag="3")]
    pub release: ::core::option::Option<Release>,
    /// A scoped, short-lived token plus the address to use it against. A provider
    /// that needs the release's rendered artifacts calls
    /// `forest.v1.RunnerService/GetReleaseFiles` (or `GetSpecFiles`) with them.
    ///
    /// Most providers act on infrastructure that already exists and need neither;
    /// both can be ignored. The token is scoped to this release alone and expires
    /// with it.
    #[prost(string, tag="4")]
    pub release_token: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub forest_addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Destination {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub environment: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub organisation: ::prost::alloc::string::String,
    /// The destination's metadata with `generic`'s own `provider_*` keys removed,
    /// so a provider sees only its own configuration.
    #[prost(map="string, string", tag="4")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Release {
    #[prost(string, tag="1")]
    pub release_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub project: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub slug: ::prost::alloc::string::String,
    /// Empty when the release has no source reference. A provider that pins an
    /// immutable artifact from the commit should fail rather than invent one.
    #[prost(string, tag="4")]
    pub reference_commit_sha: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub reference_commit_branch: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub reference_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteEvent {
    #[prost(oneof="execute_event::Event", tags="1, 2")]
    pub event: ::core::option::Option<execute_event::Event>,
}
/// Nested message and enum types in `ExecuteEvent`.
pub mod execute_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag="1")]
        Log(super::LogLine),
        #[prost(message, tag="2")]
        Outcome(super::Outcome),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogLine {
    /// "stdout" or "stderr". Anything else is treated as stdout.
    #[prost(string, tag="1")]
    pub channel: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub line: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Outcome {
    #[prost(bool, tag="1")]
    pub success: bool,
    /// Why it failed. Surfaced as the release's failure message, so it should say
    /// what went wrong and where — this is what someone reads at 3am.
    #[prost(string, tag="2")]
    pub error_message: ::prost::alloc::string::String,
    /// Plan text, for RELEASE_MODE_PLAN.
    #[prost(string, tag="3")]
    pub plan_output: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReleaseMode {
    Unspecified = 0,
    /// Execute the release.
    Deploy = 1,
    /// Dry run. Make no change; report what a deploy would do in
    /// `Outcome.plan_output`, which is what a reviewer approves.
    Plan = 2,
}
impl ReleaseMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RELEASE_MODE_UNSPECIFIED",
            Self::Deploy => "RELEASE_MODE_DEPLOY",
            Self::Plan => "RELEASE_MODE_PLAN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RELEASE_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "RELEASE_MODE_DEPLOY" => Some(Self::Deploy),
            "RELEASE_MODE_PLAN" => Some(Self::Plan),
            _ => None,
        }
    }
}
include!("forest.provider.v1.tonic.rs");
// @@protoc_insertion_point(module)