services:
  s3:
    image: minio/minio
    hostname: minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=forestadmin
      - MINIO_ROOT_PASSWORD=forestadmin
      - MINIO_DOMAIN=forest
    networks:
      default:
        aliases:
          - forest.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  aws:
    image: amazon/aws-cli
    container_name: aws-cli
    command: |
      -c "sleep 2 && \
      aws --endpoint-url http://s3:9000 s3 mb s3://forest --region eu-west-1 || exit 0"
    entrypoint: [/bin/bash]
    environment: 
      AWS_ACCESS_KEY_ID: "forestadmin"
      AWS_SECRET_ACCESS_KEY: "forestadmin"
    depends_on: 
      - s3

