// Generated by forest-sdk-codegen. Do not edit.

import {
  type ComponentService,
  type CallContext,
  type MethodDescriptor,
  MethodNotFoundError,
} from "@rawpotion/forest-sdk";

export interface DeploymentHooks {
  prepare: { description: string; input: Record<string, unknown>; output: { manifests: Manifest[] } };
  release: { description: string; input: { release_id: string }; output: Record<string, unknown> };
  rollback: { description: string; input: { release_id: string; target_revision: string } };
}

export interface Manifest {
  content: string;
  name: string;
}

export interface Spec {
  args?: string[];
  command?: string[];
  env_vars?: Record<string, string>;
  forage_nats?: { publish: { subject: string }[]; secret_name?: string; subscribe: { subject: string }[] };
  forage_postgresql?: { database_name?: string; secret_name?: string; secret_namespace?: string };
  forage_s3?: { bucket_name?: string; key_name?: string; permissions?: { owner: boolean; read: boolean; write: boolean }; quotas?: { max_objects?: number; max_size?: number }; secret_name?: string };
  health_binary?: string;
  health_host?: string;
  host: string;
  image: string;
  name: string;
  port: number;
  port_name: string;
  replicas: number;
  tag: string;
}

export interface SealInput {
  cert: string;
  env: string;
  key: string;
  value: string;
}

export interface SealOutput {
}

export interface StatusInput {
}

export interface StatusOutput {
  healthy: boolean;
}

export interface ValidateInput {
}

export interface ValidateOutput {
  errors: string[];
  valid: boolean;
}

export interface CommandHandler {
  /** Add or update a sealed secret key */
  seal(spec: Spec, input: SealInput, context: CallContext): Promise<SealOutput>;
  /** Check deployment status */
  status(spec: Spec, input: StatusInput, context: CallContext): Promise<StatusOutput>;
  /** Validate manifests */
  validate(spec: Spec, input: ValidateInput, context: CallContext): Promise<ValidateOutput>;
}

export interface ForestDeploymentPrepareInput {
}

export interface ForestDeploymentPrepareOutput {
  manifests: Manifest[];
}

export interface ForestDeploymentReleaseInput {
  release_id: string;
}

export interface ForestDeploymentReleaseOutput {
}

export interface ForestDeploymentRollbackInput {
  release_id: string;
  target_revision: string;
}

export interface ForestDeploymentHookHandler {
  /** Generate Kubernetes manifests with sealed secrets */
  prepare(spec: Spec, input: ForestDeploymentPrepareInput, context: CallContext): Promise<ForestDeploymentPrepareOutput>;
  /** Apply deployment */
  release(spec: Spec, input: ForestDeploymentReleaseInput, context: CallContext): Promise<ForestDeploymentReleaseOutput>;
  /** Roll back deployment */
  rollback(spec: Spec, input: ForestDeploymentRollbackInput, context: CallContext): Promise<void>;
}

export function createRouter(commands: CommandHandler, forestDeployment: ForestDeploymentHookHandler): ComponentService<Spec> {
  return {
    async call(method: string, spec: Spec, input: unknown, context: CallContext): Promise<unknown> {
      switch (method) {
        case "commands/seal":
          return commands.seal(spec, input as SealInput, context);
        case "commands/status":
          return commands.status(spec, input as StatusInput, context);
        case "commands/validate":
          return commands.validate(spec, input as ValidateInput, context);
        case "hooks/forest/deployment/prepare":
          return forestDeployment.prepare(spec, input as ForestDeploymentPrepareInput, context);
        case "hooks/forest/deployment/release":
          return forestDeployment.release(spec, input as ForestDeploymentReleaseInput, context);
        case "hooks/forest/deployment/rollback":
          { await forestDeployment.rollback(spec, input as ForestDeploymentRollbackInput, context); return null; }
        default:
          throw new MethodNotFoundError(method);
      }
    },

    methods(): MethodDescriptor[] {
      return [
        { name: "commands/seal", kind: "command", description: "Add or update a sealed secret key" },
        { name: "commands/status", kind: "command", description: "Check deployment status" },
        { name: "commands/validate", kind: "command", description: "Validate manifests" },
        { name: "hooks/forest/deployment/prepare", kind: "hook", topic: "forest/deployment", description: "Generate Kubernetes manifests with sealed secrets" },
        { name: "hooks/forest/deployment/release", kind: "hook", topic: "forest/deployment", description: "Apply deployment" },
        { name: "hooks/forest/deployment/rollback", kind: "hook", topic: "forest/deployment", description: "Roll back deployment" },
      ];
    },
  };
}

