// Generated by forest-sdk-codegen. Do not edit.

import {
  type ComponentService,
  type CallContext,
  type MethodDescriptor,
  MethodNotFoundError,
} from "@forest/sdk";

export interface EnvVar {
  key: string;
  value: string;
}

export interface HealthCheck {
  live?: Record<string, unknown>;
}

export interface Port {
  external: boolean;
  name: string;
  port: number;
  subdomain?: string;
}

export interface Spec {
  /** JSON field: "env_vars" */
  envVars: EnvVar[];
  /** JSON field: "health_checks" */
  healthChecks?: HealthCheck;
  name: string;
  ports: Port[];
  replicas: number;
}

export interface PrepareInput {
}

export interface PrepareOutput {
  manifests: string[];
}

export interface StatusInput {
}

export interface StatusOutput {
  healthy: boolean;
}

export interface ValidateInput {
}

export interface ValidateOutput {
  errors: string[];
  valid: boolean;
}

export interface CommandHandler {
  /** Generate Terraform configuration files */
  prepare(spec: Spec, input: PrepareInput): Promise<PrepareOutput>;
  /** Check deployment status */
  status(spec: Spec, input: StatusInput): Promise<StatusOutput>;
  /** Validate configuration */
  validate(spec: Spec, input: ValidateInput): Promise<ValidateOutput>;
}

export interface ForestDeploymentPrepareInput {
}

export interface ForestDeploymentPrepareOutput {
  manifests: string[];
}

export interface ForestDeploymentReleaseInput {
  /** JSON field: "release_id" */
  releaseId: string;
}

export interface ForestDeploymentReleaseOutput {
}

export interface ForestDeploymentRollbackInput {
  /** JSON field: "release_id" */
  releaseId: string;
  /** JSON field: "target_revision" */
  targetRevision: string;
}

export interface ForestDeploymentHookHandler {
  /** Generate Terraform files for deployment */
  prepare(spec: Spec, input: ForestDeploymentPrepareInput): Promise<ForestDeploymentPrepareOutput>;
  /** Apply Terraform configuration */
  release(spec: Spec, input: ForestDeploymentReleaseInput): Promise<ForestDeploymentReleaseOutput>;
  /** Roll back Terraform state */
  rollback(spec: Spec, input: ForestDeploymentRollbackInput): Promise<void>;
}

export function createRouter(commands: CommandHandler, forestDeployment: ForestDeploymentHookHandler): ComponentService<Spec> {
  return {
    async call(method: string, spec: Spec, input: unknown, _context: CallContext): Promise<unknown> {
      switch (method) {
        case "commands/prepare":
          return commands.prepare(spec, input as PrepareInput);
        case "commands/status":
          return commands.status(spec, input as StatusInput);
        case "commands/validate":
          return commands.validate(spec, input as ValidateInput);
        case "hooks/forest/deployment/prepare":
          return forestDeployment.prepare(spec, input as ForestDeploymentPrepareInput);
        case "hooks/forest/deployment/release":
          return forestDeployment.release(spec, input as ForestDeploymentReleaseInput);
        case "hooks/forest/deployment/rollback":
          { await forestDeployment.rollback(spec, input as ForestDeploymentRollbackInput); return null; }
        default:
          throw new MethodNotFoundError(method);
      }
    },

    methods(): MethodDescriptor[] {
      return [
        { name: "commands/prepare", kind: "command", description: "Generate Terraform configuration files" },
        { name: "commands/status", kind: "command", description: "Check deployment status" },
        { name: "commands/validate", kind: "command", description: "Validate configuration" },
        { name: "hooks/forest/deployment/prepare", kind: "hook", topic: "forest/deployment", description: "Generate Terraform files for deployment" },
        { name: "hooks/forest/deployment/release", kind: "hook", topic: "forest/deployment", description: "Apply Terraform configuration" },
        { name: "hooks/forest/deployment/rollback", kind: "hook", topic: "forest/deployment", description: "Roll back Terraform state" },
      ];
    },
  };
}

