// Generated by forest-sdk-codegen. Do not edit.
#![allow(clippy::upper_case_acronyms)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Autoscaling {
    pub max_replicas: i64,
    #[serde(default = "default_autoscaling_min_replicas")]
    pub min_replicas: i64,
    #[serde(default = "default_autoscaling_target_cpu")]
    pub target_cpu: i64,
}

fn default_autoscaling_min_replicas() -> i64 { 1 }
fn default_autoscaling_target_cpu() -> i64 { 80 }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Change {
    pub diff: String,
    pub kind: Kind,
    pub resource: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DeploymentHooks {
    pub prepare: serde_json::Value,
    pub release: serde_json::Value,
    pub rollback: serde_json::Value,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EnvVar {
    pub key: String,
    pub value: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct HealthChecks {
    pub liveness: Probe,
    #[serde(default)]
    pub readiness: Option<Probe>,
    #[serde(default)]
    pub startup: Option<Probe>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct HttpProbe {
    pub path: String,
    pub port: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Ingress {
    pub annotations: std::collections::BTreeMap<String, String>,
    pub host: String,
    #[serde(default = "default_ingress_path")]
    pub path: String,
    #[serde(default = "default_ingress_tls")]
    pub tls: bool,
}

fn default_ingress_path() -> String { "/".to_string() }
fn default_ingress_tls() -> bool { true }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Port {
    #[serde(default = "default_port_external")]
    pub external: bool,
    pub name: String,
    pub port: i64,
    pub protocol: Protocol,
}

fn default_port_external() -> bool { false }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Probe {
    #[serde(default = "default_probe_failure_threshold")]
    pub failure_threshold: i64,
    #[serde(default)]
    pub http: Option<HttpProbe>,
    #[serde(default = "default_probe_initial_delay")]
    pub initial_delay: i64,
    #[serde(default = "default_probe_period")]
    pub period: i64,
    #[serde(default)]
    pub tcp: Option<TcpProbe>,
    #[serde(default = "default_probe_timeout")]
    pub timeout: i64,
}

fn default_probe_failure_threshold() -> i64 { 3 }
fn default_probe_initial_delay() -> i64 { 10 }
fn default_probe_period() -> i64 { 10 }
fn default_probe_timeout() -> i64 { 3 }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ResourceQuantity {
    pub cpu: String,
    pub memory: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Resources {
    #[serde(default)]
    pub limits: Option<ResourceQuantity>,
    pub requests: ResourceQuantity,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SecretRef {
    #[serde(default)]
    pub env_prefix: Option<String>,
    #[serde(default)]
    pub mount_path: Option<String>,
    pub name: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ServiceMesh {
    #[serde(default = "default_servicemesh_enabled")]
    pub enabled: bool,
    #[serde(default = "default_servicemesh_mtls")]
    pub mtls: bool,
}

fn default_servicemesh_enabled() -> bool { false }
fn default_servicemesh_mtls() -> bool { true }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TcpProbe {
    pub port: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Volume {
    pub mount_path: String,
    pub name: String,
    pub source: String,
    pub volume_type: VolumeType,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Kind {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "modify")]
    Modify,
    #[serde(rename = "remove")]
    Remove,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Protocol {
    #[serde(rename = "tcp")]
    Tcp,
    #[serde(rename = "udp")]
    Udp,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Environment {
    #[serde(rename = "dev")]
    Dev,
    #[serde(rename = "staging")]
    Staging,
    #[serde(rename = "prod")]
    Prod,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum VolumeType {
    #[serde(rename = "configmap")]
    Configmap,
    #[serde(rename = "secret")]
    Secret,
    #[serde(rename = "pvc")]
    Pvc,
    #[serde(rename = "emptydir")]
    Emptydir,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Spec {
    pub annotations: std::collections::BTreeMap<String, String>,
    #[serde(default)]
    pub autoscaling: Option<Autoscaling>,
    pub env_vars: Vec<EnvVar>,
    pub environment: Environment,
    pub health_checks: HealthChecks,
    pub image: String,
    #[serde(default)]
    pub ingress: Option<Ingress>,
    pub labels: std::collections::BTreeMap<String, String>,
    pub name: String,
    #[serde(default = "default_spec_namespace")]
    pub namespace: String,
    pub ports: Vec<Port>,
    #[serde(default = "default_spec_replicas")]
    pub replicas: i64,
    pub resources: Resources,
    #[serde(default)]
    pub secrets: Option<Vec<SecretRef>>,
    #[serde(default)]
    pub service_mesh: Option<ServiceMesh>,
    #[serde(default)]
    pub volumes: Option<Vec<Volume>>,
}

fn default_spec_namespace() -> String { "default".to_string() }
fn default_spec_replicas() -> i64 { 1 }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DiffInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DiffOutput {
    pub changes: Vec<Change>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LogsInput {
    #[serde(default = "default_logsinput_container")]
    pub container: String,
    #[serde(default = "default_logsinput_lines")]
    pub lines: i64,
}

fn default_logsinput_container() -> String { "".to_string() }
fn default_logsinput_lines() -> i64 { 100 }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LogsOutput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PrepareInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PrepareOutput {
    pub manifests: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StatusInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StatusOutput {
    pub age: String,
    pub desired: i64,
    pub healthy: bool,
    pub ready: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ValidateInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ValidateOutput {
    pub errors: Vec<String>,
    pub valid: bool,
}

pub trait CommandHandler: Send + Sync {
    /// Show diff of generated manifests against live cluster state
    fn diff(&self, spec: &Spec, input: DiffInput) -> impl std::future::Future<Output = Result<DiffOutput, forest_sdk::Error>> + Send;
    /// Tail pod logs for the service
    fn logs(&self, spec: &Spec, input: LogsInput) -> impl std::future::Future<Output = Result<LogsOutput, forest_sdk::Error>> + Send;
    /// Generate Kubernetes manifests (Deployment, Service, Ingress, HPA, etc.)
    fn prepare(&self, spec: &Spec, input: PrepareInput) -> impl std::future::Future<Output = Result<PrepareOutput, forest_sdk::Error>> + Send;
    /// Check deployment status against the cluster
    fn status(&self, spec: &Spec, input: StatusInput) -> impl std::future::Future<Output = Result<StatusOutput, forest_sdk::Error>> + Send;
    /// Validate spec and generated manifests
    fn validate(&self, spec: &Spec, input: ValidateInput) -> impl std::future::Future<Output = Result<ValidateOutput, forest_sdk::Error>> + Send;
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentPrepareInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentPrepareOutput {
    pub manifests: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentReleaseInput {
    pub release_id: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentReleaseOutput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentRollbackInput {
    pub release_id: String,
    #[serde(default = "default_forestdeploymentrollbackinput_target_revision")]
    pub target_revision: String,
}

fn default_forestdeploymentrollbackinput_target_revision() -> String { "".to_string() }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestObservabilityConfigureLoggingInput {
    #[serde(default = "default_forestobservabilityconfigurelogginginput_log_level")]
    pub log_level: String,
}

fn default_forestobservabilityconfigurelogginginput_log_level() -> String { "info".to_string() }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestObservabilityConfigureLoggingOutput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestObservabilityConfigureMonitoringInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestObservabilityConfigureMonitoringOutput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestSecurityApplyPoliciesInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestSecurityApplyPoliciesOutput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestSecurityScanImageInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestSecurityScanImageOutput {
    pub critical: i64,
    pub passed: bool,
    pub vulnerabilities: i64,
}

pub trait ForestDeploymentHookHandler: Send + Sync {
    /// Generate and validate Kubernetes manifests for deployment
    fn prepare(&self, spec: &Spec, input: ForestDeploymentPrepareInput) -> impl std::future::Future<Output = Result<ForestDeploymentPrepareOutput, forest_sdk::Error>> + Send;
    /// Apply manifests to the target cluster
    fn release(&self, spec: &Spec, input: ForestDeploymentReleaseInput) -> impl std::future::Future<Output = Result<ForestDeploymentReleaseOutput, forest_sdk::Error>> + Send;
    /// Roll back to a previous revision
    fn rollback(&self, spec: &Spec, input: ForestDeploymentRollbackInput) -> impl std::future::Future<Output = Result<(), forest_sdk::Error>> + Send;
}

pub trait ForestObservabilityHookHandler: Send + Sync {
    /// Configure log collection pipeline for the service
    fn configure_logging(&self, spec: &Spec, input: ForestObservabilityConfigureLoggingInput) -> impl std::future::Future<Output = Result<ForestObservabilityConfigureLoggingOutput, forest_sdk::Error>> + Send;
    /// Create or update ServiceMonitor and PrometheusRule resources
    fn configure_monitoring(&self, spec: &Spec, input: ForestObservabilityConfigureMonitoringInput) -> impl std::future::Future<Output = Result<ForestObservabilityConfigureMonitoringOutput, forest_sdk::Error>> + Send;
}

pub trait ForestSecurityHookHandler: Send + Sync {
    /// Apply NetworkPolicy and PodSecurity resources
    fn apply_policies(&self, spec: &Spec, input: ForestSecurityApplyPoliciesInput) -> impl std::future::Future<Output = Result<ForestSecurityApplyPoliciesOutput, forest_sdk::Error>> + Send;
    /// Run vulnerability scan on the container image
    fn scan_image(&self, spec: &Spec, input: ForestSecurityScanImageInput) -> impl std::future::Future<Output = Result<ForestSecurityScanImageOutput, forest_sdk::Error>> + Send;
}

pub struct ComponentRouter<C, H1, H2, H3>
where
    C: CommandHandler + Send + Sync,
    H1: ForestDeploymentHookHandler + Send + Sync,
    H2: ForestObservabilityHookHandler + Send + Sync,
    H3: ForestSecurityHookHandler + Send + Sync,
{
    commands: C,
    hooks1: H1,
    hooks2: H2,
    hooks3: H3,
}

impl<C, H1, H2, H3> ComponentRouter<C, H1, H2, H3>
where
    C: CommandHandler + Send + Sync,
    H1: ForestDeploymentHookHandler + Send + Sync,
    H2: ForestObservabilityHookHandler + Send + Sync,
    H3: ForestSecurityHookHandler + Send + Sync,
{
    pub fn new(commands: C, hooks1: H1, hooks2: H2, hooks3: H3) -> Self {
        Self {
            commands,
            hooks1,
            hooks2,
            hooks3,
        }
    }
}

impl<C, H1, H2, H3> forest_sdk::ComponentService<Spec> for ComponentRouter<C, H1, H2, H3>
where
    C: CommandHandler + Send + Sync,
    H1: ForestDeploymentHookHandler + Send + Sync,
    H2: ForestObservabilityHookHandler + Send + Sync,
    H3: ForestSecurityHookHandler + Send + Sync,
{
    async fn call(&self, method: &str, spec: &Spec, input: serde_json::Value, _context: &forest_sdk::CallContext) -> Result<serde_json::Value, forest_sdk::Error> {
        match method {
            "commands/diff" => {
                let input: DiffInput = serde_json::from_value(input)?;
                let output = self.commands.diff(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/logs" => {
                let input: LogsInput = serde_json::from_value(input)?;
                let output = self.commands.logs(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/prepare" => {
                let input: PrepareInput = serde_json::from_value(input)?;
                let output = self.commands.prepare(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/status" => {
                let input: StatusInput = serde_json::from_value(input)?;
                let output = self.commands.status(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/validate" => {
                let input: ValidateInput = serde_json::from_value(input)?;
                let output = self.commands.validate(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/prepare" => {
                let input: ForestDeploymentPrepareInput = serde_json::from_value(input)?;
                let output = self.hooks1.prepare(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/release" => {
                let input: ForestDeploymentReleaseInput = serde_json::from_value(input)?;
                let output = self.hooks1.release(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/rollback" => {
                let input: ForestDeploymentRollbackInput = serde_json::from_value(input)?;
                self.hooks1.rollback(spec, input).await?;
                Ok(serde_json::Value::Null)
            }
            "hooks/forest/observability/configure_logging" => {
                let input: ForestObservabilityConfigureLoggingInput = serde_json::from_value(input)?;
                let output = self.hooks2.configure_logging(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/observability/configure_monitoring" => {
                let input: ForestObservabilityConfigureMonitoringInput = serde_json::from_value(input)?;
                let output = self.hooks2.configure_monitoring(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/security/apply_policies" => {
                let input: ForestSecurityApplyPoliciesInput = serde_json::from_value(input)?;
                let output = self.hooks3.apply_policies(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/security/scan_image" => {
                let input: ForestSecurityScanImageInput = serde_json::from_value(input)?;
                let output = self.hooks3.scan_image(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            other => Err(forest_sdk::Error::MethodNotFound(other.to_string())),
        }
    }

    fn methods(&self) -> Vec<forest_sdk::MethodDescriptor> {
        vec![
            forest_sdk::MethodDescriptor { name: "commands/diff".into(), kind: forest_sdk::MethodKind::Command, description: Some("Show diff of generated manifests against live cluster state".into()) },
            forest_sdk::MethodDescriptor { name: "commands/logs".into(), kind: forest_sdk::MethodKind::Command, description: Some("Tail pod logs for the service".into()) },
            forest_sdk::MethodDescriptor { name: "commands/prepare".into(), kind: forest_sdk::MethodKind::Command, description: Some("Generate Kubernetes manifests (Deployment, Service, Ingress, HPA, etc.)".into()) },
            forest_sdk::MethodDescriptor { name: "commands/status".into(), kind: forest_sdk::MethodKind::Command, description: Some("Check deployment status against the cluster".into()) },
            forest_sdk::MethodDescriptor { name: "commands/validate".into(), kind: forest_sdk::MethodKind::Command, description: Some("Validate spec and generated manifests".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/prepare".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Generate and validate Kubernetes manifests for deployment".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/release".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Apply manifests to the target cluster".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/rollback".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Roll back to a previous revision".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/observability/configure_logging".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/observability".into() }, description: Some("Configure log collection pipeline for the service".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/observability/configure_monitoring".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/observability".into() }, description: Some("Create or update ServiceMonitor and PrometheusRule resources".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/security/apply_policies".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/security".into() }, description: Some("Apply NetworkPolicy and PodSecurity resources".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/security/scan_image".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/security".into() }, description: Some("Run vulnerability scan on the container image".into()) },
        ]
    }
}

