use std::fmt::Write;

use crate::errors::CodegenResult;
use crate::ir::*;

pub fn emit(module: &Module) -> CodegenResult<String> {
    let mut out = String::with_capacity(4096);
    let ctx = Ctx {
        type_defs: &module.type_defs,
    };

    emit_header(&mut out)?;
    emit_type_defs(&mut out, &ctx)?;
    emit_spec_struct(&mut out, &ctx, &module.spec)?;
    emit_command_types(&mut out, &ctx, &module.commands)?;
    emit_command_trait(&mut out, &module.commands)?;
    emit_hook_types(&mut out, &ctx, &module.hook_groups)?;
    emit_hook_traits(&mut out, &module.hook_groups)?;
    emit_router(&mut out, module)?;

    Ok(out)
}

// ── Header ───────────────────────────────────────────────────────────

fn emit_header(out: &mut String) -> CodegenResult<()> {
    writeln!(out, "// Generated by forest-sdk-codegen. Do not edit.")?;
    // derivable_impls: a generated `impl Default` whose fields are all
    // `Default::default()` is one a derive could have written, and consumers
    // run clippy with -D warnings over this file.
    writeln!(
        out,
        "#![allow(clippy::upper_case_acronyms, clippy::derivable_impls)]"
    )?;
    writeln!(out)?;
    Ok(())
}

// ── Type definitions ─────────────────────────────────────────────────

fn emit_type_defs(out: &mut String, ctx: &Ctx) -> CodegenResult<()> {
    for td in ctx.type_defs {
        match &td.kind {
            TypeDefKind::Enum(enum_def) => emit_enum(out, &td.name, enum_def)?,
            TypeDefKind::Struct(struct_def) => emit_struct(out, ctx, &td.name, struct_def)?,
            TypeDefKind::Map(inner) => {
                let inner_type = type_ref_to_rust(inner);
                writeln!(
                    out,
                    "pub type {} = std::collections::BTreeMap<String, {}>;",
                    td.name, inner_type
                )?;
                writeln!(out)?;
            }
        }
    }
    Ok(())
}

fn emit_enum(out: &mut String, name: &str, enum_def: &EnumDef) -> CodegenResult<()> {
    match enum_def {
        EnumDef::StringEnum(variants) => {
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]"
            )?;
            writeln!(out, "pub enum {name} {{")?;
            for variant in variants {
                let variant_name = to_pascal_case(variant);
                if variant_name != *variant {
                    writeln!(out, "    #[serde(rename = \"{variant}\")]")?;
                }
                writeln!(out, "    {variant_name},")?;
            }
            writeln!(out, "}}")?;
            writeln!(out)?;
        }
        EnumDef::IntegerEnum(variants) => {
            writeln!(
                out,
                "#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]"
            )?;
            writeln!(out, "pub enum {name} {{")?;
            for val in variants {
                writeln!(out, "    #[serde(rename = \"{val}\")]")?;
                writeln!(out, "    V{val},")?;
            }
            writeln!(out, "}}")?;
            writeln!(out)?;
        }
    }
    Ok(())
}

// ── Defaults ─────────────────────────────────────────────────────────
//
// A consumer's `config` reaches a component binary WITHOUT being unified with
// `#Spec`, so every CUE default has to be reproduced here as a serde default,
// or an omitted field arrives absent and the spec fails to decode with
// "missing field". Four cases, each for a different reason:
//
// - Scalars with a CUE default: a named default fn, as before.
// - Enum fields with a default (`"a" | "b" | *"a"`): a default fn returning
//   the variant. Previously nothing, because the default is a string and the
//   field's type is the enum.
// - Lists and maps: always `#[serde(default)]`. `cue def --out openapi` DROPS
//   list and map defaults (`[...string] | *[]` emits no `default` at all), so
//   `[...T]` and `[...T] | *[]` are indistinguishable here, and empty is the
//   only default either could mean.
// - A field whose type is a named struct with every member defaultable (e.g.
//   `queue: #Queue`): `#[serde(default)]`, backed by an `impl Default` for the
//   struct built from the same default fns. The field itself is a `$ref`, so
//   its members' defaults were never visible on it.

struct Ctx<'a> {
    type_defs: &'a [TypeDef],
}

/// How a field is filled when the input omits it.
enum FieldDefault {
    /// No default: the field is genuinely required.
    None,
    /// `#[serde(default = "fn")]`, with `fn() -> ty { expr }` emitted.
    Fn { fn_name: String, expr: String },
    /// `#[serde(default)]` — the type's own `Default`.
    Trait,
}

impl Ctx<'_> {
    fn find(&self, name: &str) -> Option<&TypeDef> {
        self.type_defs.iter().find(|td| td.name == name)
    }

    fn field_default(&self, field: &Field, struct_name: &str) -> FieldDefault {
        if !field.required {
            return FieldDefault::Trait;
        }
        let fn_name =
            format!("default_{struct_name}_{}", to_snake_case(&field.name)).to_lowercase();

        if let Some(default_val) = &field.default_value
            && let Some(expr) = self.default_expr(default_val, &field.ty)
        {
            return FieldDefault::Fn { fn_name, expr };
        }

        match &field.ty {
            TypeRef::Array(_) | TypeRef::Map(_) => FieldDefault::Trait,
            // Opaque objects (including `{[string]: T} | *{}`, which lowers to
            // this) default to `{}` rather than `Value`'s own default, Null:
            // `{}` is what an omitted map means.
            TypeRef::Object(_) => FieldDefault::Fn {
                fn_name,
                expr: "serde_json::Value::Object(serde_json::Map::new())".into(),
            },
            TypeRef::Named(name) if self.is_defaultable(name, &mut Vec::new()) => {
                FieldDefault::Trait
            }
            _ => FieldDefault::None,
        }
    }

    /// A Rust expression for a CUE default, when the field's type can hold it.
    fn default_expr(&self, val: &DefaultValue, ty: &TypeRef) -> Option<String> {
        match (val, ty) {
            (DefaultValue::String(s), TypeRef::String) => {
                Some(format!("\"{}\".to_string()", escape_rust_string(s)))
            }
            (DefaultValue::Integer(n), TypeRef::Integer) => Some(format!("{n}")),
            (DefaultValue::Float(f), TypeRef::Float) => Some(format!("{f}_f64")),
            (DefaultValue::Boolean(b), TypeRef::Boolean) => Some(format!("{b}")),
            (DefaultValue::Object(v), TypeRef::Object(_)) => Some(format!(
                "serde_json::from_str(\"{}\").expect(\"generated default\")",
                escape_rust_string(&v.to_string())
            )),
            (_, TypeRef::Named(name)) => match self.find(name).map(|td| &td.kind) {
                Some(TypeDefKind::Enum(EnumDef::StringEnum(variants))) => match val {
                    DefaultValue::String(s) if variants.contains(s) => {
                        Some(format!("{name}::{}", to_pascal_case(s)))
                    }
                    _ => None,
                },
                Some(TypeDefKind::Enum(EnumDef::IntegerEnum(variants))) => match val {
                    DefaultValue::Integer(n) if variants.contains(n) => {
                        Some(format!("{name}::V{n}"))
                    }
                    _ => None,
                },
                _ => None,
            },
            _ => None,
        }
    }

    /// Whether a named type can be built with nothing in the input — and so
    /// gets an `impl Default` (structs) or already has one (maps).
    fn is_defaultable(&self, name: &str, visiting: &mut Vec<String>) -> bool {
        if visiting.iter().any(|v| v == name) {
            return false; // recursive type: never default it
        }
        match self.find(name).map(|td| &td.kind) {
            Some(TypeDefKind::Map(_)) => true,
            Some(TypeDefKind::Struct(def)) => {
                visiting.push(name.to_string());
                let all = def.fields.iter().all(|f| {
                    if !f.required
                        || f.default_value
                            .as_ref()
                            .is_some_and(|d| self.default_expr(d, &f.ty).is_some())
                    {
                        return true;
                    }
                    match &f.ty {
                        TypeRef::Array(_) | TypeRef::Map(_) | TypeRef::Object(_) => true,
                        TypeRef::Named(inner) => self.is_defaultable(inner, visiting),
                        _ => false,
                    }
                });
                visiting.pop();
                all
            }
            _ => false,
        }
    }
}

fn emit_struct(
    out: &mut String,
    ctx: &Ctx,
    name: &str,
    struct_def: &StructDef,
) -> CodegenResult<()> {
    let defaults: Vec<FieldDefault> = struct_def
        .fields
        .iter()
        .map(|f| ctx.field_default(f, name))
        .collect();

    writeln!(
        out,
        "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]"
    )?;
    writeln!(out, "pub struct {name} {{")?;
    for (field, default) in struct_def.fields.iter().zip(&defaults) {
        emit_field(out, field, default)?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Emit default value functions
    let mut any_fn = false;
    for (field, default) in struct_def.fields.iter().zip(&defaults) {
        if let FieldDefault::Fn { fn_name, expr } = default {
            let rust_type = type_ref_to_rust(&field.ty);
            writeln!(out, "fn {fn_name}() -> {rust_type} {{ {expr} }}")?;
            any_fn = true;
        }
    }
    if any_fn {
        writeln!(out)?;
    }

    // A struct that can be built from nothing gets `Default`, so a field of
    // this type elsewhere can be `#[serde(default)]`. Built from the same
    // default fns the field attributes name, so the two cannot disagree.
    if defaults.iter().all(|d| !matches!(d, FieldDefault::None)) {
        writeln!(out, "impl Default for {name} {{")?;
        writeln!(out, "    fn default() -> Self {{")?;
        writeln!(out, "        Self {{")?;
        for (field, default) in struct_def.fields.iter().zip(&defaults) {
            let rust_name = to_snake_case(&field.name);
            let init = match default {
                FieldDefault::Fn { fn_name, .. } => format!("{fn_name}()"),
                _ => "Default::default()".to_string(),
            };
            writeln!(out, "            {rust_name}: {init},")?;
        }
        writeln!(out, "        }}")?;
        writeln!(out, "    }}")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    Ok(())
}

fn emit_field(out: &mut String, field: &Field, default: &FieldDefault) -> CodegenResult<()> {
    let rust_name = to_snake_case(&field.name);
    let rust_type = type_ref_to_rust(&field.ty);
    let rust_type = if field.required {
        rust_type
    } else {
        format!("Option<{rust_type}>")
    };

    if rust_name != field.name {
        writeln!(out, "    #[serde(rename = \"{}\")]", field.name)?;
    }

    match default {
        FieldDefault::None => {}
        FieldDefault::Trait => writeln!(out, "    #[serde(default)]")?,
        FieldDefault::Fn { fn_name, .. } => writeln!(out, "    #[serde(default = \"{fn_name}\")]")?,
    }

    writeln!(out, "    pub {rust_name}: {rust_type},")?;
    Ok(())
}

/// Escape a string for use inside a Rust string literal.
fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

// ── Spec struct ──────────────────────────────────────────────────────

fn emit_spec_struct(out: &mut String, ctx: &Ctx, spec: &Spec) -> CodegenResult<()> {
    emit_struct(
        out,
        ctx,
        "Spec",
        &StructDef {
            fields: spec.fields.clone(),
        },
    )
}

// ── Command types & trait ────────────────────────────────────────────

fn emit_command_types(out: &mut String, ctx: &Ctx, commands: &[Command]) -> CodegenResult<()> {
    for cmd in commands {
        let pascal = to_pascal_case(&cmd.name);

        // Input struct
        let input_name = format!("{pascal}Input");
        emit_struct(out, ctx, &input_name, &cmd.input)?;

        // Output struct
        let output_name = format!("{pascal}Output");
        emit_struct(out, ctx, &output_name, &cmd.output)?;
    }
    Ok(())
}

fn emit_command_trait(out: &mut String, commands: &[Command]) -> CodegenResult<()> {
    if commands.is_empty() {
        return Ok(());
    }
    writeln!(out, "pub trait CommandHandler: Send + Sync {{")?;
    for cmd in commands {
        let pascal = to_pascal_case(&cmd.name);
        let snake = to_snake_case(&cmd.name);
        let input_name = format!("{pascal}Input");
        let output_name = format!("{pascal}Output");

        if !cmd.description.is_empty() {
            writeln!(out, "    /// {}", cmd.description)?;
        }
        writeln!(
            out,
            "    fn {snake}(&self, spec: &Spec, input: {input_name}) -> impl std::future::Future<Output = Result<{output_name}, forest_sdk::Error>> + Send;"
        )?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;
    Ok(())
}

// ── Hook types & traits ──────────────────────────────────────────────

fn emit_hook_types(out: &mut String, ctx: &Ctx, groups: &[HookGroup]) -> CodegenResult<()> {
    for group in groups {
        let topic_pascal = topic_to_pascal_case(&group.topic);
        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);

            // Input struct
            let input_name = format!("{topic_pascal}{action_pascal}Input");
            emit_struct(out, ctx, &input_name, &action.input)?;

            // Output struct (if present)
            if let Some(output) = &action.output {
                let output_name = format!("{topic_pascal}{action_pascal}Output");
                emit_struct(out, ctx, &output_name, output)?;
            }
        }
    }
    Ok(())
}

fn emit_hook_traits(out: &mut String, groups: &[HookGroup]) -> CodegenResult<()> {
    for group in groups {
        let topic_pascal = topic_to_pascal_case(&group.topic);
        let trait_name = format!("{topic_pascal}HookHandler");

        writeln!(out, "pub trait {trait_name}: Send + Sync {{")?;
        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);
            let snake = to_snake_case(&action.name);
            let input_name = format!("{topic_pascal}{action_pascal}Input");

            let output_type = if action.output.is_some() {
                format!("{topic_pascal}{action_pascal}Output")
            } else {
                "()".to_string()
            };

            if !action.description.is_empty() {
                writeln!(out, "    /// {}", action.description)?;
            }
            writeln!(
                out,
                "    fn {snake}(&self, spec: &Spec, input: {input_name}) -> impl std::future::Future<Output = Result<{output_type}, forest_sdk::Error>> + Send;"
            )?;
        }
        writeln!(out, "}}")?;
        writeln!(out)?;
    }
    Ok(())
}

// ── Router ───────────────────────────────────────────────────────────

fn emit_router(out: &mut String, module: &Module) -> CodegenResult<()> {
    let has_commands = !module.commands.is_empty();

    // Collect type parameter info for each hook group: (type_param, trait_name, field_name)
    let hook_params: Vec<(String, String, String)> = module
        .hook_groups
        .iter()
        .enumerate()
        .map(|(i, g)| {
            let trait_name = format!("{}HookHandler", topic_to_pascal_case(&g.topic));
            let (type_param, field_name) = if module.hook_groups.len() == 1 {
                ("H".to_string(), "hooks".to_string())
            } else {
                (format!("H{}", i + 1), format!("hooks{}", i + 1))
            };
            (type_param, trait_name, field_name)
        })
        .collect();

    // Build generic params + bounds
    let mut type_params = Vec::new();
    let mut bounds = Vec::new();
    if has_commands {
        type_params.push("C".to_string());
        bounds.push("C: CommandHandler + Send + Sync".to_string());
    }
    for (tp, trait_name, _) in &hook_params {
        type_params.push(tp.clone());
        bounds.push(format!("{tp}: {trait_name} + Send + Sync"));
    }

    let type_params_str = type_params.join(", ");
    let bounds_str = bounds.join(",\n    ");

    // ── Struct ──
    writeln!(out, "pub struct ComponentRouter<{type_params_str}>")?;
    writeln!(out, "where")?;
    writeln!(out, "    {bounds_str},")?;
    writeln!(out, "{{")?;
    if has_commands {
        writeln!(out, "    commands: C,")?;
    }
    for (tp, _, field) in &hook_params {
        writeln!(out, "    {field}: {tp},")?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;

    // ── new() constructor ──
    writeln!(
        out,
        "impl<{type_params_str}> ComponentRouter<{type_params_str}>"
    )?;
    writeln!(out, "where")?;
    writeln!(out, "    {bounds_str},")?;
    writeln!(out, "{{")?;
    {
        let mut params = Vec::new();
        if has_commands {
            params.push("commands: C".to_string());
        }
        for (tp, _, field) in &hook_params {
            params.push(format!("{field}: {tp}"));
        }
        writeln!(out, "    pub fn new({}) -> Self {{", params.join(", "))?;
    }
    writeln!(out, "        Self {{")?;
    if has_commands {
        writeln!(out, "            commands,")?;
    }
    for (_, _, field) in &hook_params {
        writeln!(out, "            {field},")?;
    }
    writeln!(out, "        }}")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // ── ComponentService impl ──
    writeln!(
        out,
        "impl<{type_params_str}> forest_sdk::ComponentService<Spec> for ComponentRouter<{type_params_str}>"
    )?;
    writeln!(out, "where")?;
    writeln!(out, "    {bounds_str},")?;
    writeln!(out, "{{")?;

    // call method (async)
    writeln!(
        out,
        "    async fn call(&self, method: &str, spec: &Spec, input: serde_json::Value, _context: &forest_sdk::CallContext) -> Result<serde_json::Value, forest_sdk::Error> {{"
    )?;
    writeln!(out, "        match method {{")?;

    // Command dispatch arms
    for cmd in &module.commands {
        let pascal = to_pascal_case(&cmd.name);
        let snake = to_snake_case(&cmd.name);
        let input_name = format!("{pascal}Input");
        let method_path = format!("commands/{}", cmd.name);
        writeln!(out, "            \"{method_path}\" => {{")?;
        writeln!(
            out,
            "                let input: {input_name} = serde_json::from_value(input)?;"
        )?;
        writeln!(
            out,
            "                let output = self.commands.{snake}(spec, input).await?;"
        )?;
        writeln!(
            out,
            "                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)"
        )?;
        writeln!(out, "            }}")?;
    }

    // Hook dispatch arms
    for (i, group) in module.hook_groups.iter().enumerate() {
        let (_, _, field) = &hook_params[i];
        let topic_pascal = topic_to_pascal_case(&group.topic);

        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);
            let snake = to_snake_case(&action.name);
            let input_name = format!("{topic_pascal}{action_pascal}Input");
            let method_path = format!("hooks/{}/{}", group.topic, action.name);

            writeln!(out, "            \"{method_path}\" => {{")?;
            writeln!(
                out,
                "                let input: {input_name} = serde_json::from_value(input)?;"
            )?;

            if action.output.is_some() {
                writeln!(
                    out,
                    "                let output = self.{field}.{snake}(spec, input).await?;"
                )?;
                writeln!(
                    out,
                    "                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)"
                )?;
            } else {
                writeln!(
                    out,
                    "                self.{field}.{snake}(spec, input).await?;"
                )?;
                writeln!(out, "                Ok(serde_json::Value::Null)")?;
            }
            writeln!(out, "            }}")?;
        }
    }

    writeln!(
        out,
        "            other => Err(forest_sdk::Error::MethodNotFound(other.to_string())),"
    )?;
    writeln!(out, "        }}")?;
    writeln!(out, "    }}")?;
    writeln!(out)?;

    // methods() method
    writeln!(
        out,
        "    fn methods(&self) -> Vec<forest_sdk::MethodDescriptor> {{"
    )?;
    writeln!(out, "        vec![")?;
    for cmd in &module.commands {
        let method_path = format!("commands/{}", cmd.name);
        let desc = escape_rust_string(&cmd.description);
        writeln!(
            out,
            "            forest_sdk::MethodDescriptor {{ name: \"{method_path}\".into(), kind: forest_sdk::MethodKind::Command, description: Some(\"{desc}\".into()) }},"
        )?;
    }
    for group in &module.hook_groups {
        for action in &group.actions {
            let method_path = format!("hooks/{}/{}", group.topic, action.name);
            let desc = escape_rust_string(&action.description);
            writeln!(
                out,
                "            forest_sdk::MethodDescriptor {{ name: \"{method_path}\".into(), kind: forest_sdk::MethodKind::Hook {{ topic: \"{}\".into() }}, description: Some(\"{desc}\".into()) }},",
                group.topic
            )?;
        }
    }
    writeln!(out, "        ]")?;
    writeln!(out, "    }}")?;

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

// ── Component metadata ───────────────────────────────────────────────

#[allow(dead_code)]
fn emit_component_metadata(out: &mut String, component: &Component) -> CodegenResult<()> {
    writeln!(
        out,
        "pub const COMPONENT_NAME: &str = \"{}\";",
        component.name
    )?;
    writeln!(
        out,
        "pub const COMPONENT_ORG: &str = \"{}\";",
        component.org
    )?;
    writeln!(
        out,
        "pub const COMPONENT_VERSION: &str = \"{}\";",
        component.version
    )?;
    writeln!(out)?;
    Ok(())
}

// ── Type mapping ─────────────────────────────────────────────────────

fn type_ref_to_rust(ty: &TypeRef) -> String {
    match ty {
        TypeRef::String => "String".to_string(),
        TypeRef::Integer => "i64".to_string(),
        TypeRef::Float => "f64".to_string(),
        TypeRef::Boolean => "bool".to_string(),
        TypeRef::Named(name) => name.clone(),
        TypeRef::Array(inner) => format!("Vec<{}>", type_ref_to_rust(inner)),
        TypeRef::Object(_) => "serde_json::Value".to_string(),
        TypeRef::Map(inner) => {
            format!(
                "std::collections::BTreeMap<String, {}>",
                type_ref_to_rust(inner)
            )
        }
    }
}

// ── Naming utilities ─────────────────────────────────────────────────

fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-', '/'])
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            let first = chars
                .next()
                .map(|c| c.to_uppercase().to_string())
                .unwrap_or_default();
            format!("{first}{}", chars.as_str())
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c == '-' || c == '/' {
            result.push('_');
        } else if c.is_uppercase() && i > 0 {
            result.push('_');
            result.extend(c.to_lowercase());
        } else {
            result.extend(c.to_lowercase());
        }
    }
    result
}

fn topic_to_pascal_case(topic: &str) -> String {
    to_pascal_case(topic)
}
