// Generated by forest-sdk-codegen. Do not edit.
#![allow(clippy::upper_case_acronyms)]

// --- Domain types ---

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Port {
    pub name: String,
    pub port: i64,
    pub protocol: Protocol,
    pub external: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Protocol {
    #[serde(rename = "tcp")]
    Tcp,
    #[serde(rename = "udp")]
    Udp,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EnvVar {
    pub key: String,
    pub value: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ResourceQuantity {
    pub cpu: String,
    pub memory: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Resources {
    pub requests: ResourceQuantity,
    pub limits: ResourceQuantity,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct HealthCheckProbe {
    pub path: String,
    pub port: i64,
    pub initial_delay_seconds: i64,
    pub period_seconds: i64,
    pub timeout_seconds: i64,
    pub failure_threshold: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct HealthChecks {
    pub liveness: HealthCheckProbe,
    pub readiness: HealthCheckProbe,
}

// --- Root Spec struct ---

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Spec {
    pub name: String,
    pub image: String,
    pub ports: Vec<Port>,
    pub replicas: i64,
    pub environment: Vec<EnvVar>,
    pub resources: Resources,
    pub health_checks: HealthChecks,
}

// --- Command I/O structs ---

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BuildInput {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BuildOutput {
    pub binary: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ValidateInput {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ValidateOutput {
    pub valid: bool,
    pub messages: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TestInput {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TestOutput {
    pub passed: i64,
    pub failed: i64,
    pub total: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DockerBuildInput {
    pub tag: String,
    #[serde(default)]
    pub registry: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DockerBuildOutput {
    pub image: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StatusInput {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StatusOutput {
    pub binary_exists: bool,
    pub git_branch: String,
    pub git_commit: String,
    pub git_dirty: bool,
}

// --- Command trait ---

pub trait CommandHandler {
    /// Compile the release binary
    fn build(&self, spec: &Spec, input: BuildInput) -> Result<BuildOutput, forest_sdk::Error>;

    /// Run clippy, fmt check, and cargo check
    fn validate(
        &self,
        spec: &Spec,
        input: ValidateInput,
    ) -> Result<ValidateOutput, forest_sdk::Error>;

    /// Run the test suite
    fn test(&self, spec: &Spec, input: TestInput) -> Result<TestOutput, forest_sdk::Error>;

    /// Build a Docker container image for the service
    fn docker_build(
        &self,
        spec: &Spec,
        input: DockerBuildInput,
    ) -> Result<DockerBuildOutput, forest_sdk::Error>;

    /// Show build artifacts, git state, and deployment info
    fn status(&self, spec: &Spec, input: StatusInput) -> Result<StatusOutput, forest_sdk::Error>;
}

// --- Hook I/O structs ---

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentPrepareInput {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentPrepareOutput {
    pub manifests: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentReleaseInput {
    pub release_id: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentReleaseOutput {
    pub deployed: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentRollbackInput {
    pub name: String,
    pub release_id: String,
}

// --- Hook trait ---

pub trait ForestDeploymentHookHandler {
    fn prepare(
        &self,
        spec: &Spec,
        input: ForestDeploymentPrepareInput,
    ) -> Result<ForestDeploymentPrepareOutput, forest_sdk::Error>;

    fn release(
        &self,
        spec: &Spec,
        input: ForestDeploymentReleaseInput,
    ) -> Result<ForestDeploymentReleaseOutput, forest_sdk::Error>;

    fn rollback(
        &self,
        spec: &Spec,
        input: ForestDeploymentRollbackInput,
    ) -> Result<(), forest_sdk::Error>;
}

// --- Router ---

pub struct ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    commands: C,
    hooks: H,
}

impl<C, H> ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    pub fn new(commands: C, hooks: H) -> Self {
        Self { commands, hooks }
    }
}

impl<C, H> forest_sdk::ComponentService<Spec> for ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    fn call(
        &self,
        method: &str,
        spec: &Spec,
        input: serde_json::Value,
    ) -> Result<serde_json::Value, forest_sdk::Error> {
        match method {
            "commands/build" => {
                let input: BuildInput = serde_json::from_value(input)?;
                let output = self.commands.build(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/validate" => {
                let input: ValidateInput = serde_json::from_value(input)?;
                let output = self.commands.validate(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/test" => {
                let input: TestInput = serde_json::from_value(input)?;
                let output = self.commands.test(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/docker-build" => {
                let input: DockerBuildInput = serde_json::from_value(input)?;
                let output = self.commands.docker_build(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/status" => {
                let input: StatusInput = serde_json::from_value(input)?;
                let output = self.commands.status(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/prepare" => {
                let input: ForestDeploymentPrepareInput = serde_json::from_value(input)?;
                let output = self.hooks.prepare(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/release" => {
                let input: ForestDeploymentReleaseInput = serde_json::from_value(input)?;
                let output = self.hooks.release(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/rollback" => {
                let input: ForestDeploymentRollbackInput = serde_json::from_value(input)?;
                self.hooks.rollback(spec, input)?;
                Ok(serde_json::Value::Null)
            }
            other => Err(forest_sdk::Error::MethodNotFound(other.to_string())),
        }
    }

    fn methods(&self) -> Vec<forest_sdk::MethodDescriptor> {
        vec![
            forest_sdk::MethodDescriptor {
                name: "commands/build".into(),
                kind: forest_sdk::MethodKind::Command,
            },
            forest_sdk::MethodDescriptor {
                name: "commands/validate".into(),
                kind: forest_sdk::MethodKind::Command,
            },
            forest_sdk::MethodDescriptor {
                name: "commands/test".into(),
                kind: forest_sdk::MethodKind::Command,
            },
            forest_sdk::MethodDescriptor {
                name: "commands/docker-build".into(),
                kind: forest_sdk::MethodKind::Command,
            },
            forest_sdk::MethodDescriptor {
                name: "commands/status".into(),
                kind: forest_sdk::MethodKind::Command,
            },
            forest_sdk::MethodDescriptor {
                name: "hooks/forest/deployment/prepare".into(),
                kind: forest_sdk::MethodKind::Hook {
                    topic: "forest/deployment".into(),
                },
            },
            forest_sdk::MethodDescriptor {
                name: "hooks/forest/deployment/release".into(),
                kind: forest_sdk::MethodKind::Hook {
                    topic: "forest/deployment".into(),
                },
            },
            forest_sdk::MethodDescriptor {
                name: "hooks/forest/deployment/rollback".into(),
                kind: forest_sdk::MethodKind::Hook {
                    topic: "forest/deployment".into(),
                },
            },
        ]
    }
}
