// Generated by forest-sdk-codegen. Do not edit.
#![allow(clippy::upper_case_acronyms)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EnvVar {
    pub key: String,
    pub value: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct HealthCheckProbe {
    #[serde(default = "default_healthcheckprobe_failure_threshold")]
    pub failure_threshold: i64,
    #[serde(default = "default_healthcheckprobe_initial_delay_seconds")]
    pub initial_delay_seconds: i64,
    #[serde(default = "default_healthcheckprobe_path")]
    pub path: String,
    #[serde(default = "default_healthcheckprobe_period_seconds")]
    pub period_seconds: i64,
    #[serde(default = "default_healthcheckprobe_port")]
    pub port: i64,
    #[serde(default = "default_healthcheckprobe_timeout_seconds")]
    pub timeout_seconds: i64,
}

fn default_healthcheckprobe_failure_threshold() -> i64 { 3 }
fn default_healthcheckprobe_initial_delay_seconds() -> i64 { 10 }
fn default_healthcheckprobe_path() -> String { "/healthz".to_string() }
fn default_healthcheckprobe_period_seconds() -> i64 { 10 }
fn default_healthcheckprobe_port() -> i64 { 8080 }
fn default_healthcheckprobe_timeout_seconds() -> i64 { 3 }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct HealthChecks {
    pub liveness: HealthCheckProbe,
    pub readiness: HealthCheckProbe,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Port {
    #[serde(default = "default_port_external")]
    pub external: bool,
    pub name: String,
    pub port: i64,
    pub protocol: Protocol,
}

fn default_port_external() -> bool { false }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Resources {
    pub limits: serde_json::Value,
    pub requests: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Protocol {
    #[serde(rename = "tcp")]
    Tcp,
    #[serde(rename = "udp")]
    Udp,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Spec {
    pub environment: Vec<EnvVar>,
    pub health_checks: HealthChecks,
    pub image: String,
    pub name: String,
    pub ports: Vec<Port>,
    #[serde(default = "default_spec_replicas")]
    pub replicas: i64,
    pub resources: serde_json::Value,
}

fn default_spec_replicas() -> i64 { 1 }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BuildInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BuildOutput {
    pub binary: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DockerBuildInput {
    #[serde(default = "default_dockerbuildinput_registry")]
    pub registry: String,
    pub tag: String,
}

fn default_dockerbuildinput_registry() -> String { "".to_string() }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DockerBuildOutput {
    pub image: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StatusInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StatusOutput {
    pub binary_exists: bool,
    pub git_branch: String,
    pub git_commit: String,
    pub git_dirty: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TestInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TestOutput {
    pub failed: i64,
    pub passed: i64,
    pub total: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ValidateInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ValidateOutput {
    pub messages: Vec<String>,
    pub valid: bool,
}

pub trait CommandHandler {
    /// Compile the release binary
    fn build(&self, spec: &Spec, input: BuildInput) -> Result<BuildOutput, forest_sdk::Error>;
    /// Build a Docker container image for the service
    fn docker_build(&self, spec: &Spec, input: DockerBuildInput) -> Result<DockerBuildOutput, forest_sdk::Error>;
    /// Show build artifacts, git state, and deployment info
    fn status(&self, spec: &Spec, input: StatusInput) -> Result<StatusOutput, forest_sdk::Error>;
    /// Run the test suite (nextest if available, else cargo test)
    fn test(&self, spec: &Spec, input: TestInput) -> Result<TestOutput, forest_sdk::Error>;
    /// Run clippy, fmt check, and cargo check
    fn validate(&self, spec: &Spec, input: ValidateInput) -> Result<ValidateOutput, forest_sdk::Error>;
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentPrepareInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentPrepareOutput {
    pub manifests: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentReleaseInput {
    pub release_id: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentReleaseOutput {
    pub deployed: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentRollbackInput {
    pub name: String,
    pub release_id: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentRollbackOutput {
}

pub trait ForestDeploymentHookHandler {
    /// Generate Kubernetes manifests for deployment
    fn prepare(&self, spec: &Spec, input: ForestDeploymentPrepareInput) -> Result<ForestDeploymentPrepareOutput, forest_sdk::Error>;
    /// Deploy the service to the target cluster
    fn release(&self, spec: &Spec, input: ForestDeploymentReleaseInput) -> Result<ForestDeploymentReleaseOutput, forest_sdk::Error>;
    /// Roll back to a previous release
    fn rollback(&self, spec: &Spec, input: ForestDeploymentRollbackInput) -> Result<ForestDeploymentRollbackOutput, forest_sdk::Error>;
}

pub struct ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    commands: C,
    hooks: H,
}

impl<C, H> ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    pub fn new(commands: C, hooks: H) -> Self {
        Self {
            commands,
            hooks,
        }
    }
}

impl<C, H> forest_sdk::ComponentService<Spec> for ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    fn call(&self, method: &str, spec: &Spec, input: serde_json::Value, _context: &forest_sdk::CallContext) -> Result<serde_json::Value, forest_sdk::Error> {
        match method {
            "commands/build" => {
                let input: BuildInput = serde_json::from_value(input)?;
                let output = self.commands.build(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/docker-build" => {
                let input: DockerBuildInput = serde_json::from_value(input)?;
                let output = self.commands.docker_build(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/status" => {
                let input: StatusInput = serde_json::from_value(input)?;
                let output = self.commands.status(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/test" => {
                let input: TestInput = serde_json::from_value(input)?;
                let output = self.commands.test(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/validate" => {
                let input: ValidateInput = serde_json::from_value(input)?;
                let output = self.commands.validate(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/prepare" => {
                let input: ForestDeploymentPrepareInput = serde_json::from_value(input)?;
                let output = self.hooks.prepare(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/release" => {
                let input: ForestDeploymentReleaseInput = serde_json::from_value(input)?;
                let output = self.hooks.release(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/rollback" => {
                let input: ForestDeploymentRollbackInput = serde_json::from_value(input)?;
                let output = self.hooks.rollback(spec, input)?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            other => Err(forest_sdk::Error::MethodNotFound(other.to_string())),
        }
    }

    fn methods(&self) -> Vec<forest_sdk::MethodDescriptor> {
        vec![
            forest_sdk::MethodDescriptor { name: "commands/build".into(), kind: forest_sdk::MethodKind::Command, description: Some("Compile the release binary".into()) },
            forest_sdk::MethodDescriptor { name: "commands/docker-build".into(), kind: forest_sdk::MethodKind::Command, description: Some("Build a Docker container image for the service".into()) },
            forest_sdk::MethodDescriptor { name: "commands/status".into(), kind: forest_sdk::MethodKind::Command, description: Some("Show build artifacts, git state, and deployment info".into()) },
            forest_sdk::MethodDescriptor { name: "commands/test".into(), kind: forest_sdk::MethodKind::Command, description: Some("Run the test suite (nextest if available, else cargo test)".into()) },
            forest_sdk::MethodDescriptor { name: "commands/validate".into(), kind: forest_sdk::MethodKind::Command, description: Some("Run clippy, fmt check, and cargo check".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/prepare".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Generate Kubernetes manifests for deployment".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/release".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Deploy the service to the target cluster".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/rollback".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Roll back to a previous release".into()) },
        ]
    }
}

