// @generated
// This file is @generated by prost-build.
// ============================================================================
// Agent → Controller
// ============================================================================

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentMessage {
    #[prost(oneof = "agent_message::Message", tags = "1, 2, 3, 4")]
    pub message: ::core::option::Option<agent_message::Message>,
}
/// Nested message and enum types in `AgentMessage`.
pub mod agent_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Register(super::AgentRegister),
        #[prost(message, tag = "2")]
        Heartbeat(super::AgentHeartbeat),
        #[prost(message, tag = "3")]
        JobUpdate(super::JobUpdate),
        #[prost(message, tag = "4")]
        LogBatch(super::JobLogBatch),
    }
}
/// First message an agent sends on the stream.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentRegister {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pool: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub total_vcpus: u32,
    #[prost(uint32, tag = "5")]
    pub total_memory_mib: u32,
    #[prost(uint32, tag = "6")]
    pub total_disk_mib: u32,
    #[prost(string, tag = "7")]
    pub kernel_version: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub firecracker_version: ::prost::alloc::string::String,
    /// Available rootfs images with semver (e.g. "terraform-v1-1.3.0")
    #[prost(string, repeated, tag = "9")]
    pub available_images: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Architecture: "x86_64" or "aarch64" (future)
    #[prost(string, tag = "10")]
    pub arch: ::prost::alloc::string::String,
}
/// Periodic keepalive with capacity info (recommended every 10s).
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AgentHeartbeat {
    #[prost(uint32, tag = "1")]
    pub active_vms: u32,
    #[prost(uint32, tag = "2")]
    pub available_vcpus: u32,
    #[prost(uint32, tag = "3")]
    pub available_memory_mib: u32,
    #[prost(uint32, tag = "4")]
    pub available_disk_mib: u32,
    #[prost(double, tag = "5")]
    pub load_1m: f64,
    #[prost(double, tag = "6")]
    pub load_5m: f64,
}
/// Status update for a running job.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobUpdate {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "JobStatus", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub plan_output: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "5")]
    pub exit_code: i32,
}
/// Batch of log lines from a running job.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobLogBatch {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub lines: ::prost::alloc::vec::Vec<LogLine>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogLine {
    /// "stdout" or "stderr"
    #[prost(string, tag = "1")]
    pub channel: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub line: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
}
// ============================================================================
// Controller → Agent
// ============================================================================

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControllerMessage {
    #[prost(oneof = "controller_message::Message", tags = "1, 2, 3")]
    pub message: ::core::option::Option<controller_message::Message>,
}
/// Nested message and enum types in `ControllerMessage`.
pub mod controller_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        RegisterAck(super::AgentRegisterAck),
        #[prost(message, tag = "2")]
        RunJob(super::RunJob),
        #[prost(message, tag = "3")]
        CancelJob(super::CancelJob),
    }
}
/// Controller response to AgentRegister.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentRegisterAck {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub accepted: bool,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
/// Dispatch a job to the agent for execution in a Firecracker microVM.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunJob {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// Rootfs image to use (e.g. "terraform-v1"). Agent resolves to
    /// highest compatible semver on disk.
    #[prost(string, tag = "2")]
    pub image: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub command: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "4")]
    pub environment:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "5")]
    pub files: ::prost::alloc::vec::Vec<JobFile>,
    /// Resource allocation
    #[prost(uint32, tag = "6")]
    pub vcpus: u32,
    #[prost(uint32, tag = "7")]
    pub memory_mib: u32,
    #[prost(uint32, tag = "8")]
    pub disk_mib: u32,
    #[prost(uint32, tag = "9")]
    pub timeout_seconds: u32,
    /// Network policy
    #[prost(bool, tag = "10")]
    pub egress_enabled: bool,
    /// Execution mode: "deploy" or "plan"
    #[prost(string, tag = "11")]
    pub mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobFile {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    /// octal, e.g. 0644
    #[prost(uint32, tag = "3")]
    pub mode: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelJob {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
// ============================================================================
// Shared enums
// ============================================================================

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JobStatus {
    Unspecified = 0,
    Pending = 1,
    Scheduling = 2,
    Booting = 3,
    Running = 4,
    Completing = 5,
    Completed = 6,
    Failed = 7,
    TimedOut = 8,
    Cancelled = 9,
}
impl JobStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "JOB_STATUS_UNSPECIFIED",
            Self::Pending => "JOB_STATUS_PENDING",
            Self::Scheduling => "JOB_STATUS_SCHEDULING",
            Self::Booting => "JOB_STATUS_BOOTING",
            Self::Running => "JOB_STATUS_RUNNING",
            Self::Completing => "JOB_STATUS_COMPLETING",
            Self::Completed => "JOB_STATUS_COMPLETED",
            Self::Failed => "JOB_STATUS_FAILED",
            Self::TimedOut => "JOB_STATUS_TIMED_OUT",
            Self::Cancelled => "JOB_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOB_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "JOB_STATUS_PENDING" => Some(Self::Pending),
            "JOB_STATUS_SCHEDULING" => Some(Self::Scheduling),
            "JOB_STATUS_BOOTING" => Some(Self::Booting),
            "JOB_STATUS_RUNNING" => Some(Self::Running),
            "JOB_STATUS_COMPLETING" => Some(Self::Completing),
            "JOB_STATUS_COMPLETED" => Some(Self::Completed),
            "JOB_STATUS_FAILED" => Some(Self::Failed),
            "JOB_STATUS_TIMED_OUT" => Some(Self::TimedOut),
            "JOB_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
include!("hollow.v1.tonic.rs");
// @@protoc_insertion_point(module)
