---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forage-secrets
  namespace: dev
spec:
  encryptedData:
    INTEGRATION_ENCRYPTION_KEY: AgAKRaiXGdKD9TYyIh03LfMUksWwV1QOHvftQy0Jm62++eR/OBQX3QiMKa9Z4+7u3uTKjcih5FfItMv9bfxFHd4CPyVfgI1mUVECZSj6Hjq/NoEDDqkevFGS5KeSo/R6tqNhl77ZFiouU/ZYvk+SIpPl4F4O/TVuW/+6y+kGScajxMgtLbkZarwyx77A8UfpxPCrUR+JzcNkOy5czBd0nk3JxpeDTEDLcIgjPQLN79mjemt9H+nv0K8X7NZkdPVEtXvLwMpoPTbNqeP+8/tTWohGrf7SRTklVfEYbdU3mwkj9VfUW2E+XV8WwXsoP8djy0z+02Xuu1IhJ99OkDVzvcpk45RiSs+VcImw6KY5ihVutMEgZ6E/EKbLedKOijE0fOluX6ns9L6QKKT07EVJbkxYvsC5k2fXfZNCWxQ0zTHe/lSdr0gmduihAuYIQkzpilveyTt0byp0NRQ3166lFoghN1hlk4EvZLl9NqNC1SS6qR6Jeo+rUViqkmH4+4I4/3qC9tG3WwTsLpd/T+ULmvkL9Xar0fWqJ8enYm2h+qlqdjNxeDIR8BX3uIHkT8wcEeyua0gyo0u0axa3lFdXRVbKdjliGE9ZFR/D806CmOcw0hiLm89nP80o061UyYRst3SNTef0tcZg9odsW6EedTyK/js5nNfYHz0uGaHgjh9zIX0GSVs9MfNN1gauS82Ju71EFP6m/XNNH50kOnbxxB1u26+8VvAqQogEMMnvtSjzJT7n7NcNV1MjBLFa
    FOREST_SERVICE_ACCOUNT_API_KEY: AgBlH4nsxZYfQbtLMoK7LCyVrF/IQL+azVREITVw/qWssrSvb9gQsznxZ1nuj/5+fmIaKgaNXRuAX5gimu9UZoWMIexRQTJGGEci5CrXHiv95Eywf4GAzd4Hfde4aRuNHVjLhObgRYNbbYIkd16nr52Vwdy6/GUA6EJ/1TLjF//vr5EqvxKq1ODOAz+K4/Ho/xJ3mI3QCwFZdQLs2VV5b4gBZz4srO9DLLrA3/0NC854ceDcyK67QCHlweRVZRE2B9oN9mGy4J0gLovR5pew9hlHxRvMgYDrw+8F26uyUzVtxDT8xFva7y6/hMu0t+lDVZTgKwJG411L1E/ds7rviHI/Ip3XcIF2YxPzd2bVHQSrIzqyqIYMifqIZVNYvBm/hZP6Y+OaUhtycwlAu+ESodXNihOIaPWct6S2/GQy83nWnPH4HFc7QXBJxcTadfM7GFq5mCp9q6aJlqFvgZjDsH3agk5VX+Yflth7Z3bPoPGtowzoK2rB67ycS/CabAKVa8fbLspFhdgAle5an7v1p4ESUkgGdB6LdYlq64BRsBJZOMjvtsRH/c1QQqEUrPuthzyA8cWaK/QBlCZp+tGFkX7M/tBkGwLi+1y5PWx5mPVpmlPostEbYOJtmuRRLxGnXn/oV9rLty+0PdIhumc0RkAoCIxMDrtVwT5hs5duMNnr1UirTB4u0hfXRX1ZIIPTMOKtoGSRUZHcjk5rNl2TyCkGNTl14IP4zjm6y58c38UWoawT2CFxdoyA4e0JFTCwDQ==
  template:
    metadata:
      name: forage-secrets
      namespace: dev
    type: Opaque
