// Generated by forest-sdk-codegen. Do not edit.

import {
  type ComponentService,
  type CallContext,
  type MethodDescriptor,
  MethodNotFoundError,
} from "@rawpotion/forest-sdk";

export interface DeploymentHooks {
  prepare: { description: string; input: Record<string, unknown>; output: { manifests: Manifest[] } };
  release: { description: string; input: { release_id: string }; output: Record<string, unknown> };
  rollback: { description: string; input: { release_id: string; target_revision: string } };
}

export interface Manifest {
  content: string;
  name: string;
}

export interface Spec {
  name: string;
  namespace: string;
}

export interface SealInput {
  cert: string;
  env: string;
  key: string;
  value: string;
}

export interface SealOutput {
}

export interface CommandHandler {
  /** Add or update a sealed secret key */
  seal(spec: Spec, input: SealInput, context: CallContext): Promise<SealOutput>;
}

export interface ForestDeploymentPrepareInput {
}

export interface ForestDeploymentPrepareOutput {
  manifests: Manifest[];
}

export interface ForestDeploymentReleaseInput {
  release_id: string;
}

export interface ForestDeploymentReleaseOutput {
}

export interface ForestDeploymentRollbackInput {
  release_id: string;
  target_revision: string;
}

export interface ForestDeploymentHookHandler {
  /** Inject sealed secrets manifest */
  prepare(spec: Spec, input: ForestDeploymentPrepareInput, context: CallContext): Promise<ForestDeploymentPrepareOutput>;
  /** No-op */
  release(spec: Spec, input: ForestDeploymentReleaseInput, context: CallContext): Promise<ForestDeploymentReleaseOutput>;
  /** No-op */
  rollback(spec: Spec, input: ForestDeploymentRollbackInput, context: CallContext): Promise<void>;
}

export function createRouter(commands: CommandHandler, forestDeployment: ForestDeploymentHookHandler): ComponentService<Spec> {
  return {
    async call(method: string, spec: Spec, input: unknown, context: CallContext): Promise<unknown> {
      switch (method) {
        case "commands/seal":
          return commands.seal(spec, input as SealInput, context);
        case "hooks/forest/deployment/prepare":
          return forestDeployment.prepare(spec, input as ForestDeploymentPrepareInput, context);
        case "hooks/forest/deployment/release":
          return forestDeployment.release(spec, input as ForestDeploymentReleaseInput, context);
        case "hooks/forest/deployment/rollback":
          { await forestDeployment.rollback(spec, input as ForestDeploymentRollbackInput, context); return null; }
        default:
          throw new MethodNotFoundError(method);
      }
    },

    methods(): MethodDescriptor[] {
      return [
        { name: "commands/seal", kind: "command", description: "Add or update a sealed secret key" },
        { name: "hooks/forest/deployment/prepare", kind: "hook", topic: "forest/deployment", description: "Inject sealed secrets manifest" },
        { name: "hooks/forest/deployment/release", kind: "hook", topic: "forest/deployment", description: "No-op" },
        { name: "hooks/forest/deployment/rollback", kind: "hook", topic: "forest/deployment", description: "No-op" },
      ];
    },
  };
}

