use std::fmt::Write;

use crate::errors::CodegenResult;
use crate::ir::*;

pub fn emit(module: &Module) -> CodegenResult<String> {
    let mut out = String::with_capacity(4096);

    emit_header(&mut out)?;
    emit_type_defs(&mut out, &module.type_defs)?;
    emit_spec_struct(&mut out, &module.spec)?;
    emit_command_types(&mut out, &module.commands)?;
    emit_command_trait(&mut out, &module.commands)?;
    emit_hook_types(&mut out, &module.hook_groups)?;
    emit_hook_traits(&mut out, &module.hook_groups)?;
    emit_router(&mut out, module)?;

    Ok(out)
}

// ── Header ───────────────────────────────────────────────────────────

fn emit_header(out: &mut String) -> CodegenResult<()> {
    writeln!(out, "// Generated by forest-sdk-codegen. Do not edit.")?;
    writeln!(out, "#![allow(clippy::upper_case_acronyms)]")?;
    writeln!(out)?;
    Ok(())
}

// ── Type definitions ─────────────────────────────────────────────────

fn emit_type_defs(out: &mut String, type_defs: &[TypeDef]) -> CodegenResult<()> {
    for td in type_defs {
        match &td.kind {
            TypeDefKind::Enum(enum_def) => emit_enum(out, &td.name, enum_def)?,
            TypeDefKind::Struct(struct_def) => emit_struct(out, &td.name, struct_def)?,
        }
    }
    Ok(())
}

fn emit_enum(out: &mut String, name: &str, enum_def: &EnumDef) -> CodegenResult<()> {
    match enum_def {
        EnumDef::StringEnum(variants) => {
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]"
            )?;
            writeln!(out, "pub enum {name} {{")?;
            for variant in variants {
                let variant_name = to_pascal_case(variant);
                if variant_name != *variant {
                    writeln!(out, "    #[serde(rename = \"{variant}\")]")?;
                }
                writeln!(out, "    {variant_name},")?;
            }
            writeln!(out, "}}")?;
            writeln!(out)?;
        }
        EnumDef::IntegerEnum(variants) => {
            writeln!(
                out,
                "#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]"
            )?;
            writeln!(out, "pub enum {name} {{")?;
            for val in variants {
                writeln!(out, "    #[serde(rename = \"{val}\")]")?;
                writeln!(out, "    V{val},")?;
            }
            writeln!(out, "}}")?;
            writeln!(out)?;
        }
    }
    Ok(())
}

fn emit_struct(out: &mut String, name: &str, struct_def: &StructDef) -> CodegenResult<()> {
    writeln!(
        out,
        "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]"
    )?;
    writeln!(out, "pub struct {name} {{")?;
    for field in &struct_def.fields {
        emit_field(out, field)?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;
    Ok(())
}

fn emit_field(out: &mut String, field: &Field) -> CodegenResult<()> {
    let rust_name = to_snake_case(&field.name);
    let rust_type = type_ref_to_rust(&field.ty);
    let rust_type = if field.required {
        rust_type
    } else {
        format!("Option<{rust_type}>")
    };

    if rust_name != field.name {
        writeln!(out, "    #[serde(rename = \"{}\")]", field.name)?;
    }
    if !field.required {
        writeln!(out, "    #[serde(default)]")?;
    }
    writeln!(out, "    pub {rust_name}: {rust_type},")?;
    Ok(())
}

// ── Spec struct ──────────────────────────────────────────────────────

fn emit_spec_struct(out: &mut String, spec: &Spec) -> CodegenResult<()> {
    writeln!(
        out,
        "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]"
    )?;
    writeln!(out, "pub struct Spec {{")?;
    for field in &spec.fields {
        emit_field(out, field)?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;
    Ok(())
}

// ── Command types & trait ────────────────────────────────────────────

fn emit_command_types(out: &mut String, commands: &[Command]) -> CodegenResult<()> {
    for cmd in commands {
        let pascal = to_pascal_case(&cmd.name);

        // Input struct
        let input_name = format!("{pascal}Input");
        emit_struct(out, &input_name, &cmd.input)?;

        // Output struct
        let output_name = format!("{pascal}Output");
        emit_struct(out, &output_name, &cmd.output)?;
    }
    Ok(())
}

fn emit_command_trait(out: &mut String, commands: &[Command]) -> CodegenResult<()> {
    if commands.is_empty() {
        return Ok(());
    }
    writeln!(out, "pub trait CommandHandler {{")?;
    for cmd in commands {
        let pascal = to_pascal_case(&cmd.name);
        let snake = to_snake_case(&cmd.name);
        let input_name = format!("{pascal}Input");
        let output_name = format!("{pascal}Output");

        if !cmd.description.is_empty() {
            writeln!(out, "    /// {}", cmd.description)?;
        }
        writeln!(
            out,
            "    fn {snake}(&self, spec: &Spec, input: {input_name}) -> Result<{output_name}, forest_sdk::Error>;"
        )?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;
    Ok(())
}

// ── Hook types & traits ──────────────────────────────────────────────

fn emit_hook_types(out: &mut String, groups: &[HookGroup]) -> CodegenResult<()> {
    for group in groups {
        let topic_pascal = topic_to_pascal_case(&group.topic);
        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);

            // Input struct
            let input_name = format!("{topic_pascal}{action_pascal}Input");
            emit_struct(out, &input_name, &action.input)?;

            // Output struct (if present)
            if let Some(output) = &action.output {
                let output_name = format!("{topic_pascal}{action_pascal}Output");
                emit_struct(out, &output_name, output)?;
            }
        }
    }
    Ok(())
}

fn emit_hook_traits(out: &mut String, groups: &[HookGroup]) -> CodegenResult<()> {
    for group in groups {
        let topic_pascal = topic_to_pascal_case(&group.topic);
        let trait_name = format!("{topic_pascal}HookHandler");

        writeln!(out, "pub trait {trait_name} {{")?;
        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);
            let snake = to_snake_case(&action.name);
            let input_name = format!("{topic_pascal}{action_pascal}Input");

            let output_type = if action.output.is_some() {
                format!("{topic_pascal}{action_pascal}Output")
            } else {
                "()".to_string()
            };

            if !action.description.is_empty() {
                writeln!(out, "    /// {}", action.description)?;
            }
            writeln!(
                out,
                "    fn {snake}(&self, spec: &Spec, input: {input_name}) -> Result<{output_type}, forest_sdk::Error>;"
            )?;
        }
        writeln!(out, "}}")?;
        writeln!(out)?;
    }
    Ok(())
}

// ── Router ───────────────────────────────────────────────────────────

fn emit_router(out: &mut String, module: &Module) -> CodegenResult<()> {
    let has_commands = !module.commands.is_empty();

    // Collect type parameter info for each hook group: (type_param, trait_name, field_name)
    let hook_params: Vec<(String, String, String)> = module
        .hook_groups
        .iter()
        .enumerate()
        .map(|(i, g)| {
            let trait_name = format!("{}HookHandler", topic_to_pascal_case(&g.topic));
            let (type_param, field_name) = if module.hook_groups.len() == 1 {
                ("H".to_string(), "hooks".to_string())
            } else {
                (format!("H{}", i + 1), format!("hooks{}", i + 1))
            };
            (type_param, trait_name, field_name)
        })
        .collect();

    // Build generic params + bounds
    let mut type_params = Vec::new();
    let mut bounds = Vec::new();
    if has_commands {
        type_params.push("C".to_string());
        bounds.push("C: CommandHandler + Send + Sync".to_string());
    }
    for (tp, trait_name, _) in &hook_params {
        type_params.push(tp.clone());
        bounds.push(format!("{tp}: {trait_name} + Send + Sync"));
    }

    let type_params_str = type_params.join(", ");
    let bounds_str = bounds.join(",\n    ");

    // ── Struct ──
    writeln!(out, "pub struct ComponentRouter<{type_params_str}>")?;
    writeln!(out, "where")?;
    writeln!(out, "    {bounds_str},")?;
    writeln!(out, "{{")?;
    if has_commands {
        writeln!(out, "    commands: C,")?;
    }
    for (tp, _, field) in &hook_params {
        writeln!(out, "    {field}: {tp},")?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;

    // ── new() constructor ──
    writeln!(
        out,
        "impl<{type_params_str}> ComponentRouter<{type_params_str}>"
    )?;
    writeln!(out, "where")?;
    writeln!(out, "    {bounds_str},")?;
    writeln!(out, "{{")?;
    {
        let mut params = Vec::new();
        if has_commands {
            params.push("commands: C".to_string());
        }
        for (tp, _, field) in &hook_params {
            params.push(format!("{field}: {tp}"));
        }
        writeln!(out, "    pub fn new({}) -> Self {{", params.join(", "))?;
    }
    writeln!(out, "        Self {{")?;
    if has_commands {
        writeln!(out, "            commands,")?;
    }
    for (_, _, field) in &hook_params {
        writeln!(out, "            {field},")?;
    }
    writeln!(out, "        }}")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // ── ComponentService impl ──
    writeln!(
        out,
        "impl<{type_params_str}> forest_sdk::ComponentService<Spec> for ComponentRouter<{type_params_str}>"
    )?;
    writeln!(out, "where")?;
    writeln!(out, "    {bounds_str},")?;
    writeln!(out, "{{")?;

    // call method
    writeln!(
        out,
        "    fn call(&self, method: &str, spec: &Spec, input: serde_json::Value) -> Result<serde_json::Value, forest_sdk::Error> {{"
    )?;
    writeln!(out, "        match method {{")?;

    // Command dispatch arms
    for cmd in &module.commands {
        let pascal = to_pascal_case(&cmd.name);
        let snake = to_snake_case(&cmd.name);
        let input_name = format!("{pascal}Input");
        let method_path = format!("commands/{}", cmd.name);
        writeln!(out, "            \"{method_path}\" => {{")?;
        writeln!(
            out,
            "                let input: {input_name} = serde_json::from_value(input)?;"
        )?;
        writeln!(
            out,
            "                let output = self.commands.{snake}(spec, input)?;"
        )?;
        writeln!(
            out,
            "                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)"
        )?;
        writeln!(out, "            }}")?;
    }

    // Hook dispatch arms
    for (i, group) in module.hook_groups.iter().enumerate() {
        let (_, _, field) = &hook_params[i];
        let topic_pascal = topic_to_pascal_case(&group.topic);

        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);
            let snake = to_snake_case(&action.name);
            let input_name = format!("{topic_pascal}{action_pascal}Input");
            let method_path = format!("hooks/{}/{}", group.topic, action.name);

            writeln!(out, "            \"{method_path}\" => {{")?;
            writeln!(
                out,
                "                let input: {input_name} = serde_json::from_value(input)?;"
            )?;

            if action.output.is_some() {
                writeln!(
                    out,
                    "                let output = self.{field}.{snake}(spec, input)?;"
                )?;
                writeln!(
                    out,
                    "                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)"
                )?;
            } else {
                writeln!(out, "                self.{field}.{snake}(spec, input)?;")?;
                writeln!(out, "                Ok(serde_json::Value::Null)")?;
            }
            writeln!(out, "            }}")?;
        }
    }

    writeln!(
        out,
        "            other => Err(forest_sdk::Error::MethodNotFound(other.to_string())),"
    )?;
    writeln!(out, "        }}")?;
    writeln!(out, "    }}")?;
    writeln!(out)?;

    // methods() method
    writeln!(
        out,
        "    fn methods(&self) -> Vec<forest_sdk::MethodDescriptor> {{"
    )?;
    writeln!(out, "        vec![")?;
    for cmd in &module.commands {
        let method_path = format!("commands/{}", cmd.name);
        writeln!(
            out,
            "            forest_sdk::MethodDescriptor {{ name: \"{method_path}\".into(), kind: forest_sdk::MethodKind::Command }},"
        )?;
    }
    for group in &module.hook_groups {
        for action in &group.actions {
            let method_path = format!("hooks/{}/{}", group.topic, action.name);
            writeln!(
                out,
                "            forest_sdk::MethodDescriptor {{ name: \"{method_path}\".into(), kind: forest_sdk::MethodKind::Hook {{ topic: \"{}\".into() }} }},",
                group.topic
            )?;
        }
    }
    writeln!(out, "        ]")?;
    writeln!(out, "    }}")?;

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

// ── Component metadata ───────────────────────────────────────────────

#[allow(dead_code)]
fn emit_component_metadata(out: &mut String, component: &Component) -> CodegenResult<()> {
    writeln!(
        out,
        "pub const COMPONENT_NAME: &str = \"{}\";",
        component.name
    )?;
    writeln!(
        out,
        "pub const COMPONENT_ORG: &str = \"{}\";",
        component.org
    )?;
    writeln!(
        out,
        "pub const COMPONENT_VERSION: &str = \"{}\";",
        component.version
    )?;
    writeln!(out)?;
    Ok(())
}

// ── Type mapping ─────────────────────────────────────────────────────

fn type_ref_to_rust(ty: &TypeRef) -> String {
    match ty {
        TypeRef::String => "String".to_string(),
        TypeRef::Integer => "i64".to_string(),
        TypeRef::Float => "f64".to_string(),
        TypeRef::Boolean => "bool".to_string(),
        TypeRef::Named(name) => name.clone(),
        TypeRef::Array(inner) => format!("Vec<{}>", type_ref_to_rust(inner)),
        TypeRef::Object(_) => "serde_json::Value".to_string(),
        TypeRef::Map(inner) => {
            format!(
                "std::collections::BTreeMap<String, {}>",
                type_ref_to_rust(inner)
            )
        }
    }
}

// ── Naming utilities ─────────────────────────────────────────────────

fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-', '/'])
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            let first = chars
                .next()
                .map(|c| c.to_uppercase().to_string())
                .unwrap_or_default();
            format!("{first}{}", chars.as_str())
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c == '-' || c == '/' {
            result.push('_');
        } else if c.is_uppercase() && i > 0 {
            result.push('_');
            result.extend(c.to_lowercase());
        } else {
            result.extend(c.to_lowercase());
        }
    }
    result
}

fn topic_to_pascal_case(topic: &str) -> String {
    to_pascal_case(topic)
}
