use std::fmt::Write;

use crate::errors::CodegenResult;
use crate::ir::*;

pub fn emit(module: &Module) -> CodegenResult<String> {
    let mut out = String::with_capacity(4096);

    emit_header(&mut out)?;
    emit_imports(&mut out)?;
    emit_type_defs(&mut out, &module.type_defs)?;
    emit_spec_interface(&mut out, &module.spec)?;
    emit_command_types(&mut out, &module.commands)?;
    emit_command_handler(&mut out, &module.commands)?;
    emit_hook_types(&mut out, &module.hook_groups)?;
    emit_hook_handlers(&mut out, &module.hook_groups)?;
    emit_router(&mut out, module)?;

    Ok(out)
}

// ── Header ───────────────────────────────────────────────────────────

fn emit_header(out: &mut String) -> CodegenResult<()> {
    writeln!(out, "// Generated by forest-sdk-codegen. Do not edit.")?;
    writeln!(out)?;
    Ok(())
}

fn emit_imports(out: &mut String) -> CodegenResult<()> {
    writeln!(out, "import {{")?;
    writeln!(out, "  type ComponentService,")?;
    writeln!(out, "  type CallContext,")?;
    writeln!(out, "  type MethodDescriptor,")?;
    writeln!(out, "  MethodNotFoundError,")?;
    writeln!(out, "}} from \"@forest/sdk\";")?;
    writeln!(out)?;
    Ok(())
}

// ── Type definitions ─────────────────────────────────────────────────

fn emit_type_defs(out: &mut String, type_defs: &[TypeDef]) -> CodegenResult<()> {
    for td in type_defs {
        match &td.kind {
            TypeDefKind::Enum(enum_def) => emit_enum(out, &td.name, enum_def)?,
            TypeDefKind::Struct(struct_def) => emit_interface(out, &td.name, struct_def)?,
            TypeDefKind::Map(inner) => {
                let inner_type = type_ref_to_ts(inner);
                writeln!(out, "export type {} = Record<string, {}>;", td.name, inner_type)?;
                writeln!(out)?;
            }
        }
    }
    Ok(())
}

fn emit_enum(out: &mut String, name: &str, enum_def: &EnumDef) -> CodegenResult<()> {
    match enum_def {
        EnumDef::StringEnum(variants) => {
            write!(out, "export type {name} = ")?;
            for (i, variant) in variants.iter().enumerate() {
                if i > 0 {
                    write!(out, " | ")?;
                }
                write!(out, "\"{}\"", escape_ts_string(variant))?;
            }
            writeln!(out, ";")?;
            writeln!(out)?;
        }
        EnumDef::IntegerEnum(variants) => {
            write!(out, "export type {name} = ")?;
            for (i, val) in variants.iter().enumerate() {
                if i > 0 {
                    write!(out, " | ")?;
                }
                write!(out, "{val}")?;
            }
            writeln!(out, ";")?;
            writeln!(out)?;
        }
    }
    Ok(())
}

fn emit_interface(out: &mut String, name: &str, struct_def: &StructDef) -> CodegenResult<()> {
    writeln!(out, "export interface {name} {{")?;
    for field in &struct_def.fields {
        emit_field(out, field)?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;
    Ok(())
}

fn emit_field(out: &mut String, field: &Field) -> CodegenResult<()> {
    let ts_name = to_camel_case(&field.name);
    let ts_type = type_ref_to_ts(&field.ty);
    let optional = if field.required { "" } else { "?" };

    if ts_name != field.name {
        writeln!(out, "  /** JSON field: \"{}\" */", field.name)?;
    }

    writeln!(out, "  {ts_name}{optional}: {ts_type};")?;
    Ok(())
}

// ── Spec interface ──────────────────────────────────────────────────

fn emit_spec_interface(out: &mut String, spec: &Spec) -> CodegenResult<()> {
    writeln!(out, "export interface Spec {{")?;
    for field in &spec.fields {
        emit_field(out, field)?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;
    Ok(())
}

// ── Command types & handler ─────────────────────────────────────────

fn emit_command_types(out: &mut String, commands: &[Command]) -> CodegenResult<()> {
    for cmd in commands {
        let pascal = to_pascal_case(&cmd.name);

        let input_name = format!("{pascal}Input");
        emit_interface(out, &input_name, &cmd.input)?;

        let output_name = format!("{pascal}Output");
        emit_interface(out, &output_name, &cmd.output)?;
    }
    Ok(())
}

fn emit_command_handler(out: &mut String, commands: &[Command]) -> CodegenResult<()> {
    if commands.is_empty() {
        return Ok(());
    }
    writeln!(out, "export interface CommandHandler {{")?;
    for cmd in commands {
        let pascal = to_pascal_case(&cmd.name);
        let camel = to_camel_case(&cmd.name);
        let input_name = format!("{pascal}Input");
        let output_name = format!("{pascal}Output");

        if !cmd.description.is_empty() {
            writeln!(out, "  /** {} */", cmd.description)?;
        }
        writeln!(
            out,
            "  {camel}(spec: Spec, input: {input_name}, context: CallContext): Promise<{output_name}>;"
        )?;
    }
    writeln!(out, "}}")?;
    writeln!(out)?;
    Ok(())
}

// ── Hook types & handlers ───────────────────────────────────────────

fn emit_hook_types(out: &mut String, groups: &[HookGroup]) -> CodegenResult<()> {
    for group in groups {
        let topic_pascal = topic_to_pascal_case(&group.topic);
        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);

            let input_name = format!("{topic_pascal}{action_pascal}Input");
            emit_interface(out, &input_name, &action.input)?;

            if let Some(output) = &action.output {
                let output_name = format!("{topic_pascal}{action_pascal}Output");
                emit_interface(out, &output_name, output)?;
            }
        }
    }
    Ok(())
}

fn emit_hook_handlers(out: &mut String, groups: &[HookGroup]) -> CodegenResult<()> {
    for group in groups {
        let topic_pascal = topic_to_pascal_case(&group.topic);
        let handler_name = format!("{topic_pascal}HookHandler");

        writeln!(out, "export interface {handler_name} {{")?;
        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);
            let camel = to_camel_case(&action.name);
            let input_name = format!("{topic_pascal}{action_pascal}Input");

            let output_type = if action.output.is_some() {
                format!("{topic_pascal}{action_pascal}Output")
            } else {
                "void".to_string()
            };

            if !action.description.is_empty() {
                writeln!(out, "  /** {} */", action.description)?;
            }
            writeln!(
                out,
                "  {camel}(spec: Spec, input: {input_name}, context: CallContext): Promise<{output_type}>;"
            )?;
        }
        writeln!(out, "}}")?;
        writeln!(out)?;
    }
    Ok(())
}

// ── Router ───────────────────────────────────────────────────────────

fn emit_router(out: &mut String, module: &Module) -> CodegenResult<()> {
    let has_commands = !module.commands.is_empty();

    // Build constructor parameters
    let mut params = Vec::new();
    if has_commands {
        params.push("commands: CommandHandler".to_string());
    }
    for group in &module.hook_groups {
        let topic_pascal = topic_to_pascal_case(&group.topic);
        let param_name = topic_to_param_name(&group.topic);
        let handler_name = format!("{topic_pascal}HookHandler");
        params.push(format!("{param_name}: {handler_name}"));
    }

    writeln!(
        out,
        "export function createRouter({}): ComponentService<Spec> {{",
        params.join(", ")
    )?;
    writeln!(out, "  return {{")?;

    // call method
    writeln!(
        out,
        "    async call(method: string, spec: Spec, input: unknown, context: CallContext): Promise<unknown> {{"
    )?;
    writeln!(out, "      switch (method) {{")?;

    for cmd in &module.commands {
        let camel = to_camel_case(&cmd.name);
        let pascal = to_pascal_case(&cmd.name);
        let input_name = format!("{pascal}Input");
        let method_path = format!("commands/{}", cmd.name);
        writeln!(out, "        case \"{method_path}\":")?;
        writeln!(
            out,
            "          return commands.{camel}(spec, input as {input_name}, context);"
        )?;
    }

    for group in &module.hook_groups {
        let param_name = topic_to_param_name(&group.topic);
        let topic_pascal = topic_to_pascal_case(&group.topic);
        for action in &group.actions {
            let camel = to_camel_case(&action.name);
            let action_pascal = to_pascal_case(&action.name);
            let input_name = format!("{topic_pascal}{action_pascal}Input");
            let method_path = format!("hooks/{}/{}", group.topic, action.name);
            writeln!(out, "        case \"{method_path}\":")?;
            if action.output.is_some() {
                writeln!(
                    out,
                    "          return {param_name}.{camel}(spec, input as {input_name}, context);"
                )?;
            } else {
                writeln!(
                    out,
                    "          {{ await {param_name}.{camel}(spec, input as {input_name}, context); return null; }}"
                )?;
            }
        }
    }

    writeln!(out, "        default:")?;
    writeln!(out, "          throw new MethodNotFoundError(method);")?;
    writeln!(out, "      }}")?;
    writeln!(out, "    }},")?;
    writeln!(out)?;

    // methods()
    writeln!(out, "    methods(): MethodDescriptor[] {{")?;
    writeln!(out, "      return [")?;
    for cmd in &module.commands {
        let method_path = format!("commands/{}", cmd.name);
        let desc = escape_ts_string(&cmd.description);
        writeln!(
            out,
            "        {{ name: \"{method_path}\", kind: \"command\", description: \"{desc}\" }},"
        )?;
    }
    for group in &module.hook_groups {
        for action in &group.actions {
            let method_path = format!("hooks/{}/{}", group.topic, action.name);
            let desc = escape_ts_string(&action.description);
            writeln!(
                out,
                "        {{ name: \"{method_path}\", kind: \"hook\", topic: \"{}\", description: \"{desc}\" }},",
                group.topic
            )?;
        }
    }
    writeln!(out, "      ];")?;
    writeln!(out, "    }},")?;

    writeln!(out, "  }};")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

// ── Type mapping ─────────────────────────────────────────────────────

fn type_ref_to_ts(ty: &TypeRef) -> String {
    match ty {
        TypeRef::String => "string".to_string(),
        TypeRef::Integer => "number".to_string(),
        TypeRef::Float => "number".to_string(),
        TypeRef::Boolean => "boolean".to_string(),
        TypeRef::Named(name) => name.clone(),
        TypeRef::Array(inner) => format!("{}[]", type_ref_to_ts(inner)),
        TypeRef::Object(_) => "Record<string, unknown>".to_string(),
        TypeRef::Map(inner) => format!("Record<string, {}>", type_ref_to_ts(inner)),
    }
}

// ── Naming utilities ─────────────────────────────────────────────────

fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-', '/'])
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            let first = chars
                .next()
                .map(|c| c.to_uppercase().to_string())
                .unwrap_or_default();
            format!("{first}{}", chars.as_str())
        })
        .collect()
}

fn to_camel_case(s: &str) -> String {
    let pascal = to_pascal_case(s);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(c) => format!("{}{}", c.to_lowercase(), chars.as_str()),
        None => String::new(),
    }
}

fn topic_to_pascal_case(topic: &str) -> String {
    to_pascal_case(topic)
}

fn topic_to_param_name(topic: &str) -> String {
    to_camel_case(topic.replace('/', "_").as_str())
}

fn escape_ts_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

// ── Dependency client generation ────────────────────────────────────

/// Generate a typed client for calling a dependency component's commands and hooks.
pub fn emit_client(module: &Module, component_id: &str) -> CodegenResult<String> {
    let mut out = String::with_capacity(2048);

    writeln!(out, "// Generated dependency client for {component_id}. Do not edit.")?;
    writeln!(out)?;
    writeln!(out, "import {{ callComponent }} from \"@forest/sdk\";")?;
    writeln!(out)?;

    // Emit type definitions (shared types like Manifest, Postgres, etc.)
    emit_type_defs(&mut out, &module.type_defs)?;

    // Emit Spec interface
    emit_spec_interface(&mut out, &module.spec)?;

    // Emit command input/output types and client functions
    for cmd in &module.commands {
        let pascal = to_pascal_case(&cmd.name);
        let input_name = format!("{pascal}Input");
        let output_name = format!("{pascal}Output");

        emit_interface(&mut out, &input_name, &cmd.input)?;
        emit_interface(&mut out, &output_name, &cmd.output)?;

        let fn_name = format!("commands{pascal}");
        let method_path = format!("commands/{}", cmd.name);

        if !cmd.description.is_empty() {
            writeln!(out, "/** {} */", cmd.description)?;
        }
        writeln!(
            out,
            "export function {fn_name}(spec: Spec, input: {input_name}): Promise<{output_name}> {{"
        )?;
        writeln!(
            out,
            "  return callComponent(\"{component_id}\", \"{method_path}\", spec, input);"
        )?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    // Emit hook input/output types and client functions
    for group in &module.hook_groups {
        let topic_pascal = topic_to_pascal_case(&group.topic);
        for action in &group.actions {
            let action_pascal = to_pascal_case(&action.name);
            let input_name = format!("{topic_pascal}{action_pascal}Input");

            emit_interface(&mut out, &input_name, &action.input)?;

            let output_type = if let Some(output) = &action.output {
                let output_name = format!("{topic_pascal}{action_pascal}Output");
                emit_interface(&mut out, &output_name, output)?;
                output_name
            } else {
                "void".to_string()
            };

            let fn_name = format!("hooks{topic_pascal}{action_pascal}");
            let method_path = format!("hooks/{}/{}", group.topic, action.name);

            if !action.description.is_empty() {
                writeln!(out, "/** {} */", action.description)?;
            }
            writeln!(
                out,
                "export function {fn_name}(spec: Spec, input: {input_name}): Promise<{output_type}> {{"
            )?;
            writeln!(
                out,
                "  return callComponent(\"{component_id}\", \"{method_path}\", spec, input);"
            )?;
            writeln!(out, "}}")?;
            writeln!(out)?;
        }
    }

    Ok(out)
}
