
apiVersion: v1
kind: Service
metadata:
  name: rust-podinfo
  namespace: rust-podinfo
  labels:
    app.kubernetes.io/name: rust-podinfo
    app.kubernetes.io/managed-by: forest
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rust-podinfo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP