// Generated by forest-sdk-codegen. Do not edit.
#![allow(clippy::upper_case_acronyms)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DeploymentHooks {
    pub prepare: serde_json::Value,
    pub release: serde_json::Value,
    pub rollback: serde_json::Value,
}

pub type EnvVars = std::collections::BTreeMap<String, String>;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct HealthCheck {
    #[serde(default)]
    pub live: Option<serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Port {
    #[serde(default = "default_port_external")]
    pub external: bool,
    pub name: String,
    pub port: i64,
    #[serde(default)]
    pub subdomain: Option<String>,
}

fn default_port_external() -> bool { false }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Spec {
    pub env_vars: EnvVars,
    #[serde(default)]
    pub health_checks: Option<HealthCheck>,
    pub name: String,
    pub ports: Vec<Port>,
    #[serde(default = "default_spec_replicas")]
    pub replicas: i64,
}

fn default_spec_replicas() -> i64 { 1 }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PrepareInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PrepareOutput {
    pub manifests: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StatusInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StatusOutput {
    pub healthy: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ValidateInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ValidateOutput {
    pub errors: Vec<String>,
    pub valid: bool,
}

pub trait CommandHandler: Send + Sync {
    /// Generate Terraform configuration files
    fn prepare(&self, spec: &Spec, input: PrepareInput) -> impl std::future::Future<Output = Result<PrepareOutput, forest_sdk::Error>> + Send;
    /// Check deployment status
    fn status(&self, spec: &Spec, input: StatusInput) -> impl std::future::Future<Output = Result<StatusOutput, forest_sdk::Error>> + Send;
    /// Validate Terraform configuration
    fn validate(&self, spec: &Spec, input: ValidateInput) -> impl std::future::Future<Output = Result<ValidateOutput, forest_sdk::Error>> + Send;
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentPrepareInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentReleaseInput {
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ForestDeploymentRollbackInput {
}

pub trait ForestDeploymentHookHandler: Send + Sync {
    /// Generate Terraform files for deployment
    fn prepare(&self, spec: &Spec, input: ForestDeploymentPrepareInput) -> impl std::future::Future<Output = Result<(), forest_sdk::Error>> + Send;
    /// Apply Terraform configuration
    fn release(&self, spec: &Spec, input: ForestDeploymentReleaseInput) -> impl std::future::Future<Output = Result<(), forest_sdk::Error>> + Send;
    /// Roll back Terraform state
    fn rollback(&self, spec: &Spec, input: ForestDeploymentRollbackInput) -> impl std::future::Future<Output = Result<(), forest_sdk::Error>> + Send;
}

pub struct ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    commands: C,
    hooks: H,
}

impl<C, H> ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    pub fn new(commands: C, hooks: H) -> Self {
        Self {
            commands,
            hooks,
        }
    }
}

impl<C, H> forest_sdk::ComponentService<Spec> for ComponentRouter<C, H>
where
    C: CommandHandler + Send + Sync,
    H: ForestDeploymentHookHandler + Send + Sync,
{
    async fn call(&self, method: &str, spec: &Spec, input: serde_json::Value, _context: &forest_sdk::CallContext) -> Result<serde_json::Value, forest_sdk::Error> {
        match method {
            "commands/prepare" => {
                let input: PrepareInput = serde_json::from_value(input)?;
                let output = self.commands.prepare(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/status" => {
                let input: StatusInput = serde_json::from_value(input)?;
                let output = self.commands.status(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "commands/validate" => {
                let input: ValidateInput = serde_json::from_value(input)?;
                let output = self.commands.validate(spec, input).await?;
                serde_json::to_value(output).map_err(forest_sdk::Error::Deserialization)
            }
            "hooks/forest/deployment/prepare" => {
                let input: ForestDeploymentPrepareInput = serde_json::from_value(input)?;
                self.hooks.prepare(spec, input).await?;
                Ok(serde_json::Value::Null)
            }
            "hooks/forest/deployment/release" => {
                let input: ForestDeploymentReleaseInput = serde_json::from_value(input)?;
                self.hooks.release(spec, input).await?;
                Ok(serde_json::Value::Null)
            }
            "hooks/forest/deployment/rollback" => {
                let input: ForestDeploymentRollbackInput = serde_json::from_value(input)?;
                self.hooks.rollback(spec, input).await?;
                Ok(serde_json::Value::Null)
            }
            other => Err(forest_sdk::Error::MethodNotFound(other.to_string())),
        }
    }

    fn methods(&self) -> Vec<forest_sdk::MethodDescriptor> {
        vec![
            forest_sdk::MethodDescriptor { name: "commands/prepare".into(), kind: forest_sdk::MethodKind::Command, description: Some("Generate Terraform configuration files".into()) },
            forest_sdk::MethodDescriptor { name: "commands/status".into(), kind: forest_sdk::MethodKind::Command, description: Some("Check deployment status".into()) },
            forest_sdk::MethodDescriptor { name: "commands/validate".into(), kind: forest_sdk::MethodKind::Command, description: Some("Validate Terraform configuration".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/prepare".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Generate Terraform files for deployment".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/release".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Apply Terraform configuration".into()) },
            forest_sdk::MethodDescriptor { name: "hooks/forest/deployment/rollback".into(), kind: forest_sdk::MethodKind::Hook { topic: "forest/deployment".into() }, description: Some("Roll back Terraform state".into()) },
        ]
    }
}

